export {};
// 설명용 체험 상태는 이 페이지 안에서만 유지한다. 실제 API에 쓰지 않는다.
const host=document.querySelector<HTMLElement>('.experience');
if(host){
const el=(id:string)=>document.getElementById(id)!;
const money=(n:number)=>Math.round(n).toLocaleString('ko-KR');
const badge=(s:string,kind='')=>`<span class="exp-badge ${kind}">${s}</span>`;
const row=(a:string,b:string)=>`<div class="exp-row"><span>${a}</span><b>${b}</b></div>`;
const action=(text:string)=>`<button type="button" class="exp-action" data-advance>${text}<span>↗</span></button>`;
const person=(name:string,detail:string,status:string)=>`<div class="exp-person"><span class="exp-avatar">${name.slice(-2)}</span><div><b>${name}</b><small>${detail}</small></div>${badge(status)}</div>`;
type Chapter={name:string,title:string,desc:string,steps:string[],roles:string[],view:(step:number)=>string,note?:string};
let chapter=0,step=0,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches&&localStorage.getItem('chukchuk-reduce-motion')!=='1',visible=false,deadline=0;
let wageKind='시급',deduct='공제 없음',weekday=3,branch='전체 매장';
const days=['일','월','화','수','목','금','토'];
const chapters:Chapter[]=[
{name:'월간 스케줄',title:'고정 요일을 정해 두면,\n다음 근무표도 수월하게.',desc:'고정 요일과 시간을 정해 근무를 반복 등록하고, 완성한 근무표를 직원에게 공개해요.',steps:['근무 요일 설정','월간 편성 보기','직원에게 공개'],roles:['사장님','사장님','직원'],note:'월간 자동 편성 버튼은 개선 예정 흐름입니다. 현재 앱에서는 반복 근무 등록·템플릿·주별 공개를 이용할 수 있어요.',view:s=>s===0?`<div class="exp-panel"><h4>민지의 고정 근무</h4>${person('김민지','홀 · 시급제','재직 중')}<p>근무하는 요일을 눌러 보세요</p><div class="exp-days">${days.map((d,i)=>`<button type="button" data-day="${i}" aria-pressed="${i===weekday}">${d}</button>`).join('')}</div>${row('근무 시간','17:00 — 22:00')}${row('반복','매주 '+days[weekday]+'요일')}${action('다음 달 자동 편성 보기')}</div>`:s===1?`<div class="exp-panel"><div class="exp-panel-title"><h4>11월 월간 근무표</h4>${badge('고정 요일 반영')}</div><div class="exp-calendar">${days.map(d=>`<b>${d}</b>`).join('')}${Array.from({length:30},(_,i)=>`<div style="--i:${i}"><small>${i+1}</small>${i%7===weekday?'<span>민지<br>17–22</span>':''}</div>`).join('')}</div>${action('직원에게 근무표 공개')}</div>`:`<div class="exp-phone-card"><p>민지님의 11월</p><h4>새 근무표가 도착했어요.</h4>${[0,1,2,3].map(i=>person('김민지',`11월 ${weekday+1+i*7}일 · ${days[weekday]}요일 17:00–22:00`,'내 근무')).join('')}${badge('사장님이 공개한 근무표')}${action('다음 기능 보기')}</div>`},
{name:'QR 출퇴근',title:'찍는 순간 기록돼요.\n점장이 옆에 없어도.',desc:'직원이 매장 QR로 직접 출퇴근해요. 분 단위 기록을 남기고, 사장님은 예정 시간과 실제 시간을 비교해요.',steps:['매장 QR 확인','출근 기록','근무시간 반영'],roles:['직원','직원','사장님'],view:s=>s===0?`<div class="exp-split"><div class="exp-panel"><h4>오늘의 내 근무</h4>${row('예정 출근','17:00')}${row('예정 퇴근','22:00')}${badge('민지 · 홀')}<div class="exp-scan"><span>⌗</span><i></i><p>매장의 QR을 확인해요</p></div>${action('QR로 출근 찍어보기')}</div><aside><b>기록을 대신 부탁할 필요 없이.</b><p>직원이 직접 찍으면 출근 시각이 남아요. 빠진 기록은 정정을 요청하고 사장님이 확인해요.</p></aside></div>`:s===1?`<div class="exp-phone-card"><span class="exp-success">✓</span><h4>17:01, 출근했어요.</h4>${row('근무 예정','17:00 — 22:00')}${row('실제 출근','17:01')}${badge('예정 시각보다 1분 늦음','amber')}<p>지각 표시는 매장의 허용 오차 설정에 따라 달라져요.</p>${action('퇴근 후 기록 보기')}</div>`:`<div class="exp-panel"><h4>출퇴근 기록 → 급여 계산 근거</h4>${person('김민지','11월 4일 · 홀','퇴근 완료')}${row('실제 기록','17:01 — 22:03')}${row('휴게 시간','30분')}${row('기록상 근무 시간','4시간 32분')}<div class="exp-timeline"><span>예정</span><i></i><span>실제</span><i></i></div><p>인정 시간은 매장 설정과 승인된 정정을 반영해 확인해요.</p>${action('급여 계산 보기')}</div>`},
{name:'급여·엑셀',title:'시급은 시급대로.\n월급은 월급대로, 척척.',desc:'근무표와 출퇴근 기록을 대조하고, 직원별 임금 조건과 공제 내역을 확인해 마감해요. 계산 근거도 함께 남아요.',steps:['임금·공제 설정','계산 근거 확인','엑셀로 내보내기'],roles:['사장님','사장님','사장님'],view:s=>{const gross=wageKind==='월급'?2500000:1200000,cut=deduct==='3.3%'?gross*.033:deduct==='4대보험'?112000:0;return s===0?`<div class="exp-panel"><h4>직원별 급여 조건</h4><label>임금 방식<select id="exp-wage"><option ${wageKind==='시급'?'selected':''}>시급</option><option ${wageKind==='월급'?'selected':''}>월급</option></select></label>${row(wageKind+' 금액',wageKind==='시급'?'12,000원':'2,500,000원')}<label>공제 방식<select id="exp-deduct">${['공제 없음','4대보험','3.3%'].map(v=>`<option ${v===deduct?'selected':''}>${v}</option>`).join('')}</select></label><p>직원의 소득 유형과 가입 조건을 확인해 설정해요. 보험료 예시는 실제 고지액과 다를 수 있어요.</p>${action('이 조건으로 계산 보기')}</div>`:s===1?`<div class="exp-split"><div class="exp-panel"><h4>민지 · 11월 급여 근거</h4>${row('임금 방식',wageKind)}${row('기본 급여',money(gross)+'원')}${row('공제 · '+deduct,'−'+money(cut)+'원')}<div class="exp-total"><small>예시 실수령액</small><strong>${money(gross-cut)}<em>원</em></strong></div>${action('급여 자료 내보내기')}</div><aside><b>월말에 다시 계산하지 않도록.</b><p>확정 전에 근무 기록과 공제 내역을 확인하고, 직원에게 계산 근거를 보여 주세요.</p><p>예시에는 주휴·가산·추가 수당을 포함하지 않았어요.</p></aside></div>`:`<div class="exp-panel"><h4>급여 자료를 한 번에.</h4><div class="exp-sheet"><div>직원</div><div>지급액</div><div>공제액</div><div>실수령액</div><div>김민지</div><div>${money(gross)}</div><div>${money(cut)}</div><div>${money(gross-cut)}</div><div>박준호</div><div>2,500,000</div><div>개별 설정</div><div>확인 완료</div></div><button class="exp-action" id="exp-export" type="button">예시 급여표 다운로드 <span>↓</span></button><p>체험에서는 엑셀로 열 수 있는 CSV 예시를 내려받아요. 실제 앱의 급여 내보내기는 앱에서 이용하세요.</p>${action('계약·명세서 보기')}</div>`}},
{name:'계약·명세서',title:'계약할 때도, 월급 줄 때도.\n서류까지 이어져요.',desc:'직원별 근로조건으로 계약서를 준비하고, 확정한 급여의 명세서를 확인해요. 필요한 서류를 기록과 함께 관리해요.',steps:['근로조건 확인','계약서 초안','급여명세서'],roles:['사장님','사장님','직원'],view:s=>`<div class="exp-paper"><p class="exp-paper-label">${s<2?'근로계약서 준비':'급여명세서 · 11월'}</p><h4>${s===0?'근로조건부터 확인해요':s===1?'조건이 채워진 계약서 초안':'내 월급, 항목별로 확인해요'}</h4>${row('직원','김민지')}${s<2?row('근무 장소','우리 가게 · 본점')+row('근무일',days[weekday]+'요일')+row('근무 시간','17:00 — 22:00')+row('임금','시급 12,000원'):row('기본 급여','1,200,000원')+row('공제','직원별 설정 반영')+row('지급일','11월 30일')}${s===1?'<div class="exp-sign"><span>사장님 · 서명 전</span><span>직원 · 서명 전</span></div><p>내용을 검토하고 서명을 진행해요. 이 체험에서는 서명되지 않습니다.</p>':''}${action(s===0?'계약서 초안 보기':s===1?'급여명세서 보기':'대타·교대 보기')}</div>`},
{name:'대타·교대',title:'갑자기 생긴 빈자리.\n요청부터 승인까지 여기서.',desc:'직원이 대타나 교대를 요청하면 동료가 수락해요. 사장님 승인 후 근무표에 반영돼요.',steps:['직원이 요청','동료가 수락','사장님 확인','근무표 반영'],roles:['직원 · 민지','직원 · 준호','사장님','사장님'],view:s=>`<div class="exp-panel"><div class="exp-panel-title"><h4>11월 4일 · 대타 요청</h4>${badge(s===0?'작성 중':s===1?'모집 중':s===2?'사장님 승인 대기':'승인 완료')}</div>${person('김민지','수요일 17:00–22:00','원래 근무')}${s>0?person('박준호','같은 매장 · 근무 가능',s===1?'수락 가능':s===2?'수락 완료':'대타 배정'):''}<div class="exp-message">“개인 일정이 생겼어요. 이 시간 대신 일할 수 있나요?”</div><div class="exp-flow"><span class="done">요청</span><i>→</i><span class="${s>0?'done':''}">동료 수락</span><i>→</i><span class="${s>2?'done':''}">사장님 승인</span></div>${s===3?row('반영된 근무표','준호 · 17:00–22:00'):''}<p>${s===3?'수락만으로 근무가 바뀌지 않아요. 사장님 승인 후 반영돼요.':'요청과 수락 상태를 앱에서 함께 확인해요.'}</p>${action(s===0?'대타 요청 올리기':s===1?'준호가 대타 수락하기':s===2?'사장님이 승인하기':'직원 급여 화면 보기')}</div>`},
{name:'직원 화면',title:'“제 월급 얼마예요?”\n직원이 직접 확인해요.',desc:'가입한 직원은 자신의 근무표와 출퇴근, 급여와 명세서를 확인해요. 계산이 궁금하면 근거부터 열어 보면 돼요.',steps:['내 근무 확인','내 급여 확인','계산 근거 열기'],roles:['직원','직원','직원'],view:s=>`<div class="exp-phone-card"><p>안녕하세요, 민지님.</p><h4>${s===0?'오늘은 17시에 만나요.':s===1?'11월 내 급여':'어떻게 계산됐나요?'}</h4>${s===0?person('김민지','오늘 · 17:00–22:00','내 근무'):s===1?'<div class="exp-total"><small>예시 지급액 · 공제 전</small><strong>1,200,000<em>원</em></strong></div>':row('인정 근무','100시간')+row('시급','12,000원')+row('기본 급여','100시간 × 12,000원')}${s>0?row('명세서','11월 · 확인 가능'):row('공개된 근무표','11월 근무 확인 가능')}${action(s===0?'내 급여 열기':s===1?'계산 근거 열기':'매장 매뉴얼 보기')}</div>`},
{name:'매장 매뉴얼',title:'처음 온 직원에게도,\n우리 가게 방식이 보이게.',desc:'오픈 순서, 마감 체크, 기본 수칙을 사진과 단계별 설명으로 남겨요. 신입도 필요한 내용을 찾아볼 수 있어요.',steps:['수칙 찾기','단계별 확인','업무 준비'],roles:['직원','직원','직원'],note:'사진·설명 매뉴얼은 현재 기능입니다. 영상 매뉴얼은 추가 예정입니다.',view:s=>`<div class="exp-panel"><h4>${s===0?'우리 매장 매뉴얼':'오픈 준비 · 기본 수칙'}</h4><div class="exp-manual-tabs">${badge('오픈')}${badge('마감')}${badge('기본 수칙')}</div>${s===0?['오픈 전 위생 점검','음료 제조 순서','마감 정리 방법'].map((v,i)=>person('0'+(i+1),v,'단계별 안내')).join(''):`<div class="exp-instruction"><span class="exp-step-number">${s===1?'01':'02'}</span><div><b>${s===1?'손을 씻고 도구를 준비해요':'체크한 뒤 영업을 시작해요'}</b><p>${s===1?'비누로 손을 씻고, 앞치마와 집기를 확인해요. 매장 사진을 함께 등록해 위치를 알려 주세요.':'오픈 전 냉장고 온도와 매대 상태를 확인해요. 설명이 바뀌면 매뉴얼을 수정해 함께 공유해요.'}</p></div></div>`}<p>사진·설명 매뉴얼 제공 · 영상 매뉴얼 추가 예정</p>${action(s===0?'오픈 매뉴얼 열기':s===1?'다음 준비 단계':'여러 매장 보기')}</div>`},
{name:'모든 매장',title:'가게가 여러 곳이어도,\n사장님 화면은 하나.',desc:'매장을 바꿔 가며 근무 현황과 인건비를 확인해요. 확인이 필요한 기록으로 바로 이동해요.',steps:['매장 전체 보기','매장 선택','확인할 기록'],roles:['사장님','사장님','사장님'],view:s=>`<div class="exp-panel"><div class="exp-panel-title"><h4>${s===2?'확인이 필요한 기록':'오늘의 매장 현황'}</h4><label class="exp-select-label">매장<select id="exp-branch">${['전체 매장','본점','2호점'].map(v=>`<option ${branch===v?'selected':''}>${v}</option>`).join('')}</select></label></div>${s===2?person('김민지','본점 · 출근 시간 정정 요청','확인 필요'):(branch==='전체 매장'?['본점','2호점']:[branch]).map((v,i)=>`<div class="exp-store"><div><b>${v}</b>${badge('영업 중')}</div>${row('오늘 근무',i?'3명':'4명')}${row('출근 확인',i?'3명':'3명')}${row('확인할 기록',i?'없음':'1건')}</div>`).join('')}${action(s===0?'매장별 현황 확인':s===1?'확인할 기록 열기':'처음부터 다시 보기')}</div>`}
];
function render(animate=true){
 const c=chapters[chapter]; host!.dataset.chapter=String(chapter); host!.dataset.step=String(step);
 el('exp-eyebrow').textContent=`${String(chapter+1).padStart(2,'0')} / ${c.name}`;
 el('exp-title').textContent=c.title; el('exp-desc').textContent=c.desc; el('exp-role').textContent=c.roles[step];
 el('exp-screen').innerHTML=c.view(step); el('exp-screen').classList.toggle('exp-enter',animate);
 el('exp-steps').innerHTML=c.steps.map((v,i)=>`<button type="button" data-step="${i}" aria-current="${i===step?'step':'false'}"><b>${i+1}</b>${v}</button>`).join('');
 el('exp-count').textContent=`${chapter+1} / ${chapters.length}`;
 host!.querySelector('.exp-chapters')!.innerHTML=chapters.map((v,i)=>`<button type="button" data-chapter="${i}" aria-pressed="${i===chapter}"><span>${String(i+1).padStart(2,'0')}</span>${v.name}<i>↗</i></button>`).join('');
 el('exp-feedback').textContent=c.note||''; deadline=Date.now()+6500;
 el('exp-play').textContent=playing?'자동 재생 멈추기':'자동 재생 시작';el('exp-play').setAttribute('aria-pressed',String(playing));
}
function next(){if(step<chapters[chapter].steps.length-1)step++;else{chapter=(chapter+1)%chapters.length;step=0}render()}
function pause(){playing=false;el('exp-play').textContent='자동 재생 시작';el('exp-play').setAttribute('aria-pressed','false')}
host.addEventListener('click',e=>{const b=(e.target as Element).closest<HTMLButtonElement>('button');if(!b)return;
 if(b.id==='exp-play'){playing=!playing;deadline=Date.now()+6500;render(false);return}
 if(b.id==='exp-zoom'){const on=host!.classList.toggle('exp-expanded');b.textContent=on?'확대 닫기':'화면 확대';b.setAttribute('aria-expanded',String(on));return}
 pause();if(b.dataset.chapter!==undefined){chapter=+b.dataset.chapter;step=0;render()}
 else if(b.dataset.step!==undefined){step=+b.dataset.step;render()}
 else if(b.dataset.day!==undefined){weekday=+b.dataset.day;render(false)}
 else if(b.hasAttribute('data-advance')||b.id==='exp-next')next();
 else if(b.id==='exp-prev'){if(step>0)step--;else{chapter=(chapter+chapters.length-1)%chapters.length;step=chapters[chapter].steps.length-1}render()}
 else if(b.id==='exp-export'){const gross=wageKind==='월급'?2500000:1200000,cut=deduct==='3.3%'?gross*.033:deduct==='4대보험'?112000:0;const url=URL.createObjectURL(new Blob(['\uFEFF직원,임금방식,지급액,공제액,실수령액\r\n김민지,'+wageKind+','+gross+','+cut+','+(gross-cut)+'\r\n'],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='척척사장-예시급여.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);el('exp-feedback').textContent='예시 급여표를 내려받았어요. 실제 직원 자료는 포함하지 않습니다.'}
});
host.addEventListener('change',e=>{pause();const t=e.target as HTMLSelectElement;if(t.id==='exp-wage')wageKind=t.value;if(t.id==='exp-deduct')deduct=t.value;if(t.id==='exp-branch'){branch=t.value;step=1}render(false)});
host.addEventListener('focusin',()=>pause());
document.addEventListener('keydown',e=>{if(e.key==='Escape'){host!.classList.remove('exp-expanded');el('exp-zoom').textContent='화면 확대';el('exp-zoom').setAttribute('aria-expanded','false')}});
new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;deadline=Date.now()+6500},{threshold:.15}).observe(host);
setInterval(()=>{if(playing&&visible&&!document.hidden&&Date.now()>=deadline)next()},350);
render(false);
}
