import {personalTeam} from '../lib/personal-team';
import {PersonalSchedule} from './personal-schedule';
import {AttendanceScan} from './attendance-scan';
import {CorrectionFields} from './correction-fields';
import {correctionInputError,koreanInstant} from '../lib/correction-input';
'use client';
import {standardContractDraft,STANDARD_CONTRACT_SOURCE} from '@/lib/contract-template';
import {Operations} from './operations';
import {useEffect,useState,type ReactNode} from 'react';
import {type Team,type Member,memberSchema,insuranceNames,won,retirement,today,kdate,calculate} from '@/lib/team-model';
import {laborSources} from '@/lib/labor-guide';
export function Field({label,children}:{label:string,children:ReactNode}){return <label className="t-field"><span>{label}</span>{children}</label>}
export function Badge({children,tone='neutral'}:{children:ReactNode,tone?:string}){return <span className={'badge '+tone}>{children}</span>}
export function Btn({children,onClick,primary=false,disabled=false}:{children:ReactNode,onClick?:()=>void,primary?:boolean,disabled?:boolean}){return <button type="button" className={primary?'primary':'secondary'} onClick={onClick} disabled={disabled}>{children}</button>}
export function saveFile(name:string,content:string,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
export function slip(r:any,m:string,d:string,store:string){return [store+' · '+m+' 급여명세서','이름: '+r.name+' / 직원번호: '+r.employeeId,'지급일: '+d,...r.earnings.map((i:any)=>`${i.name}  ${won(i.amount)}원\n  계산: ${i.formula}`),'지급 합계: '+won(r.gross)+'원',...r.deductions.map((i:any)=>`${i.name}  ${won(i.amount)}원\n  계산: ${i.formula}`),'공제 합계: '+won(r.deduction)+'원','실수령액: '+won(r.net)+'원',r.note].join('\n\n')}
export function MemberForm({initial,state,busy,save,onDirtyChange,startStep=0,contracts=true}:{contracts?:boolean,startStep?:number,initial:Member,state:Team,busy:boolean,save:(m:Member)=>void,onDirtyChange?:(dirty:boolean)=>void}){
 const [m,setM]=useState(structuredClone(initial)),[step,setStep]=useState(startStep),[details,setDetails]=useState(false);
 useEffect(()=>{onDirtyChange?.(JSON.stringify(m)!==JSON.stringify(initial))},[m,initial,onDirtyChange]);
 const [formErrors,setFormErrors]=useState<Record<string,string>>({});
 const submit=()=>{const parsed=memberSchema.safeParse(m);if(!parsed.success){setFormErrors(Object.fromEntries(parsed.error.issues.map(i=>[String(i.path[0]),i.path[0]==='email'?'이메일 주소를 확인해 주세요.':i.path[0]==='joined'?'입사일을 확인해 주세요.':'입력값을 확인해 주세요.'])));return;}setFormErrors({});save(parsed.data)};
 const field=(k:keyof Member,v:any)=>setM({...m,[k]:v});const contract=(k:string,v:any)=>setM({...m,contract:{...m.contract,[k]:v}});
 const input=(label:string,k:keyof Member,type='text')=><Field label={label}><input type={type} value={String(m[k]??'')} onInput={e=>field(k,type==='number'?Number(e.currentTarget.value):e.currentTarget.value)} onChange={e=>field(k,type==='number'?Number(e.target.value):e.target.value)} aria-invalid={!!formErrors[k]} aria-describedby={formErrors[k]?'error-'+k:undefined}/>{formErrors[k]&&<small id={'error-'+k} role="alert" className="field-error">{formErrors[k]}</small>}</Field>;
 const select=(label:string,k:keyof Member,options:string[])=><Field label={label}><select value={String(m[k])} onChange={e=>field(k,e.target.value)}>{options.map(v=><option key={v}>{v}</option>)}</select></Field>;
 return <><div className="t-stepbar">{['01 기본 정보','02 근로조건·계약','03 소득·보험'].map((v,i)=><button className={step===i?'active':''} onClick={()=>setStep(i)} key={v}>{v}</button>)}</div><div className="t-modalbody"><div className="t-formgrid">{step===0&&<>{input('이름 *','name')}{input('이메일 * · 명세서·계약서 수신','email','email')}{input('연락처 *','phone','tel')}{select('급여 기준','payType',['시급','월급','일급'])}{input('약속한 급여 (원)','wage','number')}<div className="t-full"><Btn onClick={()=>setDetails(!details)}>{details?'기본 항목만 보기':'입사일·역할 등 더 입력하기'}</Btn></div>{details&&<>{input('입사일','joined','date')}<Field label="소속 지점"><select value={m.branchId} onChange={e=>field('branchId',e.target.value)}>{state.branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></Field>{select('업무','role',['홀','주방','매니저'])}{select('역할 · 계정 연결 후 적용','access',['직원','중간관리자'])}{m.access==='중간관리자'&&<fieldset className="t-full"><legend>매니저에게 맡길 업무 · 소속 지점만</legend>{[['schedule','근무표 등록'],['attendance','출퇴근 수정 승인'],['leave','휴가 승인 (유료)'],['notices','지점 공지 작성']].map(([key,label])=><label className="t-check" key={key}><input type="checkbox" checked={m.managerPermissions.includes(key as any)} onInput={e=>field('managerPermissions',e.currentTarget.checked?[...m.managerPermissions,key]:m.managerPermissions.filter(x=>x!==key))} onChange={e=>field('managerPermissions',e.target.checked?[...m.managerPermissions,key]:m.managerPermissions.filter(x=>x!==key))}/>{label}</label>)}<small>본인 요청 승인·다른 지점 관리·권한 재위임은 불가합니다. 체크를 해제하고 저장하면 권한을 회수합니다.</small></fieldset>}{select('재직 상태','status',['입사 준비','재직','퇴사'])}{input('휴가 잔여일 · 확인값','leaveBalance','number')}<Field label="인사 메모"><textarea value={m.notes} onChange={e=>field('notes',e.target.value)}/></Field></>}</>}
 {step===1&&!contracts&&<div className="notice">근로계약서 작성은 사장님 5부터 이용할 수 있어요. <a href="/account">요금제 확인 →</a></div>}{step===1&&contracts&&<>{m.contract.status==='체결 완료'&&<div className="notice">체결된 계약을 수정하려면 계약서 화면에서 변경 계약 작성을 시작하세요.</div>}{select('근로 형태','employment',['기간의 정함 없음','기간제','단시간','일용','독립 용역'])}{input('계약 종료일 · 없으면 비움','endDate','date')}{select('급여 형태','payType',['시급','월급','일급'])}{input('약정 금액 (원)','wage','number')}{input('매월 지급일 (1–31)','payDay','number')}{input('주 소정근로시간','weeklyHours','number')}{[['사업주 *','employer'],['근무장소 *','workplace'],['담당 업무','duties'],['근무 요일','workDays'],['휴일','holiday'],['휴가 기준','leave'],['지급 방법','paymentMethod']].map(([l,k])=><Field label={l} key={k}><input value={(m.contract as any)[k]} onInput={e=>contract(k,e.currentTarget.value)} onChange={e=>contract(k,e.target.value)}/></Field>)}{[['출근','start','time'],['퇴근','end','time'],['휴게 (분)','breakMinutes','number']].map(([l,k,t])=><Field label={l} key={k}><input type={t} value={(m.contract as any)[k]} onInput={e=>contract(k,t==='number'?Number(e.currentTarget.value):e.currentTarget.value)} onChange={e=>contract(k,t==='number'?Number(e.target.value):e.target.value)}/></Field>)}<Field label="계약 진행"><select value={m.contract.status} disabled={m.contract.status==='체결 완료'} onChange={e=>contract('status',e.target.value)}>{['작성 전','검토 중','서명 대기',...(m.contract.status==='체결 완료'?['체결 완료']:[])].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="추가 약정"><textarea value={m.contract.additional} onChange={e=>contract('additional',e.target.value)}/></Field><div className="t-full notice"><h3>표준근로계약서 참고 초안</h3><a href={STANDARD_CONTRACT_SOURCE} target="_blank" rel="noreferrer">고용노동부 원문·서식 보기 ↗</a><p>입력한 조건을 초안에 채운 뒤 직접 수정할 수 있어요. 조건을 바꾼 경우 아래 초안 내용도 확인해 주세요.</p>{!m.contract.draftText&&<Btn disabled={m.contract.status==='체결 완료'} onClick={()=>contract('draftText',standardContractDraft(state,m))}>표준서식으로 초안 채우기</Btn>}<Field label="계약서 초안 직접 수정"><textarea rows={14} maxLength={20000} disabled={m.contract.status==='체결 완료'} value={m.contract.draftText} onChange={e=>contract('draftText',e.target.value)}/></Field><small>빈칸·수당·휴게시간 등 실제 약속을 확인하세요. 서명된 원본은 별도로 보관합니다.</small></div></>}
 {step===2&&<>{select('실제 소득 구분','income',['미검토','근로소득','사업소득','기타소득'])}{select('원천징수 방식','taxMode',['직접 입력','사업소득 3.3%','공제 없음·근거 확인'])}<Field label="소득 구분·공제 제외 확인 근거"><textarea value={m.taxReason} onChange={e=>field('taxReason',e.target.value)}/></Field><div className="notice">3.3%나 보험 제외는 임의 선택으로 적용되지 않습니다. 실제 근로관계와 각각의 가입 요건을 확인하세요. 보험료는 급여 공제 항목에서 입력합니다.</div>{insuranceNames.map(n=><div className="t-insurancefield" key={n}><Field label={n}><select value={m.insurances[n]?.status||'확인 필요'} onChange={e=>field('insurances',{...m.insurances,[n]:{status:e.target.value,reason:m.insurances[n]?.reason||''}})}>{['확인 필요','가입','적용 제외'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="확인 근거 · 제외 시 필수"><input value={m.insurances[n]?.reason||''} onChange={e=>field('insurances',{...m.insurances,[n]:{status:m.insurances[n]?.status||'확인 필요',reason:e.target.value}})}/></Field></div>)}</>}</div></div>{Object.keys(formErrors).length>0&&<p className="field-error" role="alert">입력값을 확인해 주세요. 다른 단계의 항목도 확인할 수 있어요.</p>}<div className="dialog-actions">{step===0&&<Btn primary disabled={busy||!m.name.trim()||!m.email||!m.phone||m.wage<=0} onClick={submit}>{busy?'저장 중…':state.employees.some(e=>e.id===m.id)?'직원 정보 저장':'먼저 직원 등록하기'}</Btn>}<Btn disabled={!step} onClick={()=>setStep(step-1)}>이전</Btn>{step<2?<Btn onClick={()=>setStep(step+1)}>{step===0?'근로조건 보기':'소득·보험 보기'}</Btn>:<Btn primary disabled={busy} onClick={submit}>직원 정보 저장</Btn>}</div></>
}
export function Retirement({employees}:{employees:Member[]}){const [id,setId]=useState(employees[0]?.id||''),[end,setEnd]=useState(today()),[wages,setWages]=useState(0),[days,setDays]=useState(90),[ordinary,setOrdinary]=useState(0);const e=employees.find(x=>x.id===id)||employees[0],r=e?retirement(e,end,wages,days,ordinary):null;return <div className="t-columns"><section className="panel"><div className="panel-heading"><h2>산정 조건 입력</h2></div><div className="t-panelbody t-formgrid"><Field label="직원"><select value={e?.id||''} onChange={v=>setId(v.target.value)}>{employees.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></Field><Field label="퇴직일 (마지막 근무 다음 날)"><input type="date" value={end} onChange={v=>setEnd(v.target.value)}/></Field><Field label="산정기간 임금 총액 (원)"><input type="number" min="0" value={wages} onChange={v=>setWages(Number(v.target.value))}/></Field><Field label="직전 3개월 산정일수"><input type="number" min="1" max="100" value={days} onChange={v=>setDays(Number(v.target.value))}/></Field><Field label="1일 통상임금 (원)"><input type="number" min="0" value={ordinary} onChange={v=>setOrdinary(Number(v.target.value))}/></Field></div></section><section className="panel"><div className="panel-heading"><h2>퇴직금 예상</h2><Badge tone="amber">조건 검토용</Badge></div><div className="t-panelbody">{e&&r?<><dl className="t-facts"><div><dt>입사일 / 재직일수</dt><dd>{e.joined} / {r.tenure}일</dd></div><div><dt>계약 형태</dt><dd>{e.employment} · 주 {e.weeklyHours}시간</dd></div><div><dt>기준 1일 임금</dt><dd>{won(r.daily)}원</dd></div></dl><div className="t-retiretotal">{won(r.estimate)}<small>원</small></div><p>{r.eligible?'입력 조건상 기본 요건 해당':'입력 조건상 기본 요건 미충족 · 실제 근로관계 확인 필요'}</p><small>1일 기준임금 × 30 × {r.tenure} ÷ 365</small></>:<p>먼저 직원을 등록하세요.</p>}<div className="notice t-gap">저장된 주 소정근로시간을 이용한 추정입니다. 실제 4주 평균·제외 기간·상여금·퇴직연금 제도를 반영해 최종 확인하세요. 용역 명칭만으로 근로자성이 배제되지 않습니다.</div><a href={laborSources.retirement} target="_blank" rel="noreferrer">고용노동부 계산기에서 확인 ↗</a></div></section></div>}
export function SettingsPanel({state,connected,busy,save}:{state:Team,connected:boolean,busy:boolean,save:(s:Team)=>void}){const [d,setD]=useState(structuredClone(state)),[branchName,setBranchName]=useState('');const setting=(k:string,v:any)=>setD({...d,settings:{...d.settings,[k]:v}});return <><section className="panel"><div className="panel-heading"><h2>매장·사업주 정보</h2></div><div className="t-panelbody t-formgrid"><Field label="매장명"><input value={d.store.name} onChange={e=>setD({...d,store:{...d.store,name:e.target.value}})}/></Field><Field label="사업주 성명"><input value={d.settings.employerName} onInput={e=>setting('employerName',e.currentTarget.value)} onChange={e=>setting('employerName',e.target.value)}/></Field></div></section><section className="panel t-gap"><div className="panel-heading"><h2>지점 관리</h2><Badge>{d.branches.length}개</Badge></div><div className="t-panelbody">{d.branches.map((b,i)=><div className="t-formgrid t-gap-small" key={b.id}><Field label="지점 이름"><input value={b.name} onChange={e=>setD({...d,branches:d.branches.map((x,j)=>i===j?{...x,name:e.target.value}:x)})}/></Field><Field label="주소"><input value={b.address} onChange={e=>setD({...d,branches:d.branches.map((x,j)=>i===j?{...x,address:e.target.value}:x)})}/></Field></div>)}<div className="t-inline t-gap"><input aria-label="추가 지점명" placeholder="새 지점 이름" value={branchName} onInput={e=>setBranchName(e.currentTarget.value)} onChange={e=>setBranchName(e.target.value)}/><Btn onClick={()=>{if(!branchName.trim())return;setD({...d,branches:[...d.branches,{id:crypto.randomUUID(),name:branchName.trim(),address:''}]});setBranchName('')}}>+ 지점 추가</Btn></div></div></section><section className="panel t-gap"><div className="panel-heading"><h2>이메일·세무사 전달</h2><Badge tone={connected?'green':'amber'}>{connected?'서비스 연결됨':'서비스 연결 대기'}</Badge></div><div className="t-panelbody"><div className="t-formgrid"><Field label="세무사 / 사무소 이름"><input value={d.settings.accountantName} onInput={e=>setting('accountantName',e.currentTarget.value)} onChange={e=>setting('accountantName',e.target.value)}/></Field><Field label="세무사 수신 이메일"><input type="email" value={d.settings.accountantEmail} onInput={e=>setting('accountantEmail',e.currentTarget.value)} onChange={e=>setting('accountantEmail',e.target.value)}/></Field></div>{[['autoPayslip','급여 확정 시 직원별 명세서 자동 준비'],['autoContract','서면 체결 확인 시 계약 내용 사본 자동 준비'],['autoAccountant','급여 확정 시 세무사 자료 자동 준비']].map(([k,l])=><label className="t-check" key={k}><input type="checkbox" checked={(d.settings as any)[k]} onInput={e=>setting(k,e.currentTarget.checked)} onChange={e=>setting(k,e.target.checked)}/>{l}</label>)}<p className="footnote">문서는 전송함에 준비됩니다. 실제 전송은 검증된 발신 주소와 이메일 서비스 연결이 필요합니다. 이메일을 변경했으면 기존 대기 문서의 수신 주소도 확인하세요.</p></div></section><div className="t-gap"><Btn primary disabled={busy} onClick={()=>save(d)}>설정 저장</Btn></div></>}
export function StaffPortal({state,selfId,access,actor,mutate,busy,onChanged,demo=false,contracts=true}:{contracts?:boolean,demo?:boolean,onChanged:()=>void,state:Team,selfId:string,access:string,actor:any,mutate:(b:any)=>Promise<boolean>,busy:boolean}){
 state=personalTeam(state,selfId);
 const [scanKind,setScanKind]=useState('');
 const [tab,setTab]=useState(()=>({schedule:'내 근무표',employees:'내 근무표',payroll:'내 급여',contracts:'내 계약',operations:'휴가·공지'} as Record<string,string>)[new URLSearchParams(location.search).get('screen')||'']||'내 근무'),[f,setF]=useState<any>(null),[month,setMonth]=useState(today().slice(0,7));const self=state.employees.find(e=>e.id===selfId)!;
 const requestedBranch=new URLSearchParams(location.search).get('branch'),wrongBranch=!!requestedBranch&&requestedBranch!==self.branchId;
 const todayShifts=state.shifts.filter(x=>x.employeeId===selfId&&x.date===today());
 const rows=state.attendance.filter(a=>a.employeeId===selfId),active=rows.find(a=>!a.end),run=Object.values(state.payrollRuns).find((r:any)=>r.month===month&&r.locked&&r.rows.some((row:any)=>row.employeeId===selfId)) as any,pay=run?.rows.find((r:any)=>r.employeeId===selfId),demoPay=demo?calculate(state,month).find(r=>r.employeeId===selfId):null;
 return <div className="t-staff"><header className="t-staffhead"><strong>척척사장봇</strong><span>{state.store.name} · {state.branches.find(b=>b.id===self.branchId)?.name}</span><Badge tone="green">{self.name} · {self.access}</Badge></header><main className="t-staffmain"><h1>안녕하세요, {self.name}님</h1><p className="t-muted">내 출퇴근, 근무표, 급여를 여기서 확인해요.</p><div className="t-guide-tabs t-gap">{['내 근무','내 근무표','내 급여','내 계약','휴가·공지'].map(t=><button className={tab===t?'active':''} aria-pressed={tab===t} key={t} onClick={()=>{setTab(t);setF(null);if(demo){const q=new URLSearchParams(location.search);q.set('screen',({'내 근무':'attendance','내 근무표':'schedule','내 급여':'payroll','내 계약':'contracts','휴가·공지':'operations'} as Record<string,string>)[t]);history.replaceState(null,'',location.pathname+'?'+q)}}}>{t}</button>)}</div>
 {tab==='휴가·공지'&&(demo?<p className="notice">휴가 신청과 공지는 내 가게에서 이용해 주세요.</p>:<Operations onChanged={onChanged}/>)}
 {access==='manager'&&<p className="notice"><a href="/manager">위임받은 매니저 업무 열기 →</a></p>}{tab==='내 근무'&&<><section className="panel t-panelbody">{wrongBranch&&<p role="alert" className="notice">다른 매장의 QR입니다. 사장님께 우리 매장 QR을 확인해 주세요.</p>}<p>오늘 근무: {todayShifts.length?todayShifts.map(x=>x.start+'–'+x.end+(x.end<=x.start?' (다음 날)':'')).join(' · '):'등록된 일정이 없어요. 사장님께 확인해 주세요.'}</p><h2>{active?active.breakStart?'휴게 중입니다.':'근무 중입니다.':rows.some(a=>a.end&&kdate(a.start)===today())?'오늘 근무를 마쳤어요.':'출근 전입니다.'}</h2><div className="t-wrapactions t-gap">{(active?active.breakStart?[['resume','휴게 종료'],['out','퇴근']]:[['break','휴게 시작'],['out','퇴근']]:[['in',rows.some(a=>a.end&&kdate(a.start)===today())?'다시 출근':'출근']]).map(([kind,l])=><Btn primary disabled={busy||wrongBranch} key={kind} onClick={()=>['in','out'].includes(kind)?setScanKind(kind):mutate({action:'attendance',employeeId:selfId,kind})}>{l}</Btn>)}</div>{scanKind&&<AttendanceScan branchId={self.branchId} kind={scanKind} demo={demo} busy={busy} onClose={()=>setScanKind('')} onConfirm={qrToken=>mutate({action:'attendance',employeeId:selfId,kind:scanKind,qrToken})}/>}</section></>}
 {tab==='내 근무'&&<section className="panel t-gap"><div className="panel-heading"><h2>내 출퇴근 기록</h2></div>{rows.slice().reverse().slice(0,100).map(a=><div className="t-row" key={a.id}><div className="t-grow"><b>{state.employees.find(e=>e.id===a.employeeId)?.name} · {new Date(a.start).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})}</b><small>{new Date(a.start).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul'})} → {a.end?new Date(a.end).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul'}):'근무 중'} · 휴게 {Math.round(a.breakMinutes)}분</small></div><Btn disabled={state.requests.some(r=>r.before.id===a.id&&r.status==='승인 대기')} onClick={()=>setF({id:a.id,start:toKoreanInput(a.start),end:a.end?toKoreanInput(a.end):'',breakMinutes:Math.round(a.breakMinutes),reason:''})}>{state.requests.some(r=>r.before.id===a.id&&r.status==='승인 대기')?'확인 기다리는 중':'수정 요청'}</Btn></div>)}{!rows.length&&<p className="t-panelbody">아직 출퇴근 기록이 없어요. 출근을 누르면 여기에 기록돼요.</p>}{f&&<div className="t-panelbody"><h3>출퇴근 수정 요청</h3><CorrectionFields value={f} onChange={setF}/><div className="t-wrapactions t-gap"><Btn onClick={()=>setF(null)}>취소</Btn><Btn primary disabled={busy||!!correctionInputError(f)} onClick={async()=>{if(await mutate({action:'request',...f,start:koreanInstant(f.start),end:f.end?koreanInstant(f.end):null}))setF(null)}}>수정 요청 보내기</Btn></div><p className="footnote">{actor.name}님의 이름과 변경 전후가 기록됩니다. 승인 전에는 원본이 바뀌지 않습니다.</p></div>}<div className="t-panelbody"><h3>내 요청 처리 상태</h3>{!state.requests.length&&<p>아직 보낸 요청이 없어요. 잘못된 출퇴근 기록이 있다면 수정 요청을 눌러 주세요.</p>}{state.requests.map(r=><p key={r.id}>{r.reason} · <Badge>{r.status}</Badge></p>)}</div></section>}
 {tab==='내 근무표'&&<PersonalSchedule shifts={state.shifts} selfId={selfId}/>}
 {tab==='내 급여'&&<><Field label="급여 월"><input type="month" value={month} onInput={e=>setMonth(e.currentTarget.value)} onChange={e=>setMonth(e.target.value)}/></Field><section className="panel t-panelbody t-gap">{pay?<><pre className="t-document">{slip(pay,month,run.payDate,state.store.name)}</pre><div className="t-gap"><Btn onClick={()=>saveFile(month+'-급여명세서.txt',slip(pay,month,run.payDate,state.store.name))}>명세서 내려받기</Btn></div></>:demoPay?<><p className="notice">급여명세서 예시 · 실제 지급 내역이 아니에요.</p><pre className="t-document">{slip(demoPay,month,month+'-10',state.store.name)}</pre><small>예시 근무 기록으로 계산한 미확정 금액입니다. 실제 매장에서는 사장님이 확정한 명세서만 직원에게 보여요.</small></>:<p>선택한 월의 급여가 아직 확정되지 않았습니다.</p>}</section></>}
 {tab==='내 계약'&&!demo&&<p className="notice"><a href="/contracts">내 전자계약서 확인·서명하기 →</a></p>}{tab==='내 계약'&&!contracts&&<p className="notice">이 매장은 계약서 기능을 사용하지 않아요. 사장님께 사본을 요청해 주세요.</p>}{tab==='내 계약'&&contracts&&<section className="panel t-panelbody"><pre className="t-document">{contractSummary(state,self)}</pre><div className="t-gap"><Btn onClick={()=>saveFile('근로조건확인서.txt',contractSummary(state,self))}>사본 내려받기</Btn></div><p className="footnote">전자서명한 원본과 양측 서명 기록은 내 전자계약서에서 확인하세요. 아래 내용은 현재 입력된 근로조건입니다.</p></section>}
 </main></div>
}
function toKoreanInput(v:string){const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date(v));const time=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v));return date+'T'+time}
import {contractText as contractSummary} from '@/lib/team-model';


