import {useCallback,useEffect,useRef,useState} from 'react';
import {Building2,Users,TrendingUp,ClipboardCheck,RefreshCw,ArrowUpRight,ShieldCheck,X} from 'lucide-react';
import {money} from '../lib/plans';
import type {AdminStore} from '../lib/admin-overview';
const planNames:Record<string,string>={basic:'베이직',pro:'프로',legacy:'기존 매장'};
const statusNames:Record<string,string>={active:'이용 중',trialing:'체험 중',expired:'체험 종료',cancelled:'체험 중단',legacy:'기존 이용'};
const time=(v:string|null)=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'기록 없음';
const defaults={q:'',plan:'',status:'',attention:'',biz:''};
export function AdminDesk(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[filters,setFilters]=useState(defaults),[page,setPage]=useState(0),[loading,setLoading]=useState(true),[denied,setDenied]=useState(false),[busy,setBusy]=useState(false),[selected,setSelected]=useState<AdminStore|null>(null),[note,setNote]=useState(''),[status,setStatus]=useState('미확인'),[message,setMessage]=useState(''),[saveError,setSaveError]=useState('');
 const listRef=useRef<HTMLElement>(null),dialog=useRef<HTMLDialogElement>(null),sequence=useRef(0);
 const load=useCallback(async()=>{const seq=++sequence.current;setLoading(true);setError('');try{const r=await fetch('/api/admin?'+new URLSearchParams({...filters,page:String(page)}));const d:any=await r.json();if(seq!==sequence.current)return;if(r.status===403){setDenied(true);setData(null);return}if(!r.ok)throw Error(d.error);setDenied(false);setData(d)}catch(e){if(seq===sequence.current)setError(e instanceof Error?e.message:'연결을 확인해 주세요.')}finally{if(seq===sequence.current)setLoading(false)}},[page,filters]);
 useEffect(()=>{void load();return ()=>{sequence.current++}},[load]);
 useEffect(()=>{if(selected&&!dialog.current?.open)dialog.current?.showModal()},[selected]);
 function filter(key:keyof typeof defaults,value:string){setPage(0);setFilters(v=>({...v,[key]:value}));setMessage('')}
 function attention(value:string){setSearch('');setPage(0);setFilters({...defaults,attention:value});listRef.current?.scrollIntoView({block:'start'})}
 function open(s:AdminStore){setSelected(s);setNote(s.support.note);setStatus(s.support.status);setSaveError('');setMessage('')}
 async function save(){if(busy||!selected)return;setBusy(true);setSaveError('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'support',id:selected.id,version:selected.version,note,status})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setSelected(null);setMessage('본사 관리 메모를 저장했습니다.');await load()}catch(e){setSaveError(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setBusy(false)}}
 if(denied)return <main className="auth-card hq-access"><ShieldCheck size={32}/><h1>본사 운영 계정으로 들어오세요</h1><p>본사 관리에 연결한 이메일로 로그인해 주세요. 일반 고객 계정에는 관리자 권한이 없어요.</p><a className="saas-primary" href="/admin/login">관리자 이메일로 로그인</a><button className="saas-secondary" onClick={load}>로그인 후 다시 확인</button><a className="saas-back" href="/signin-with-chatgpt?return_to=%2Fadmin">기존 운영 계정으로 연결 →</a><a className="saas-back" href="/app">내 매장으로 돌아가기 →</a></main>;
 const t=data?.overview.totals;
 return <main className="hq-desk"><header className="hq-heading"><div><span className="hq-eyebrow"><ShieldCheck size={16}/> 본사 전용</span><h1>운영 현황 한눈에</h1><p>가게가 얼마나 늘었는지, 어디에 도움이 필요한지 확인하세요.</p></div><div className="hq-tools"><button className="saas-secondary" onClick={load} disabled={loading||busy}><RefreshCw size={16}/>{loading?'확인 중…':'새로 확인'}</button><a href={data?.adminAuthMethod==='email'?'/logout?next=/admin/login':'/signout-with-chatgpt?return_to=%2Fadmin'}>운영 계정 로그아웃</a></div></header><nav className="hq-nav" aria-label="관리자 화면 바로가기"><a href="#hq-overview">전체 현황</a><a href="#hq-billing">요금·결제</a><a href="#hq-customers">고객 가게</a></nav>
 {error&&<p className="saas-error" role="alert">{error}</p>}{message&&<p className="saas-success" role="status">{message}</p>}{!data&&loading&&<p role="status">운영 현황을 불러오고 있어요.</p>}
 {data&&<><section id="hq-overview" className="hq-metrics" aria-label="전체 고객 기준 주요 현황">{[{name:'가입한 가게 계정',value:t.customers,unit:'곳',hint:`운영 매장 ${money(t.branches)}곳 · 지점 포함`,Icon:Building2},{name:'등록 직원',value:t.employees,unit:'명',hint:'재직·입사 준비 기준 · 퇴사 제외',Icon:Users},{name:'최근 30일 새 가게',value:t.newCustomers30d,unit:'곳',hint:'가게 개설일 기준',Icon:TrendingUp},{name:'확인이 필요한 가게',value:t.attentionStores,unit:'곳',hint:'신청·기록 정정·체험 종료 등',Icon:ClipboardCheck}].map(c=><article className="hq-panel hq-metric" key={c.name}><div><span>{c.name}</span><c.Icon size={21}/></div><strong>{money(c.value)}<small>{c.unit}</small></strong><small>{c.hint}</small></article>)}</section>
 <ServiceNoticeAdmin/><HqAccessLog/><section className="hq-panel"><div className="hq-section-title"><div><h2>지금 확인할 일</h2><p>항목을 누르면 해당 가게만 모아 보여드려요.</p></div><button onClick={()=>attention('all')}>전체 확인 <ArrowUpRight size={16}/></button></div><div className="hq-queue">{[{key:'joins',name:'직원 가입 대기',value:t.pendingJoins,unit:'건'},{key:'corrections',name:'출퇴근 정정 대기',value:t.pendingCorrections,unit:'건'},{key:'trial',name:'7일 안에 체험 종료',value:t.trialEnding,unit:'곳'},{key:'capacity',name:'직원 한도 도달',value:t.employeeCapacity,unit:'곳'},{key:'mail',name:'이메일 발송 확인',value:t.failedMail,unit:'건'},{key:'support',name:'본사 확인 중',value:t.supportOpen,unit:'곳'}].map(q=><button key={q.key} onClick={()=>attention(q.key)}><span>{q.name}</span><strong>{money(q.value)}<small>{q.unit}</small></strong><ArrowUpRight size={17}/></button>)}</div></section>
 <section id="hq-billing" className="hq-panel"><div className="hq-section-title"><div><h2>요금제와 결제</h2><p>요금표 기준 금액과 실제 결제 실적을 구분합니다.</p></div><span className="hq-badge">결제 서비스 연결 전</span></div><div className="hq-finance"><div><span>실제 결제 매출</span><strong>연결 전</strong><small>카드 결제·환불·미납 기록을 아직 받지 않습니다.</small></div><div><span>체험 중 가게의 월 요금 합계</span><strong>{money(t.trialMonthlyQuote)}<small>원</small></strong><small>유료 기능 체험 {t.trialing}곳 · VAT 포함 · 청구액이 아닙니다.</small></div><div><span>이용 중(결제)</span><strong>{money(t.free)}<small>곳</small></strong><small>유료 체험 종료·중단 {money(t.expired)}곳</small></div></div><div className="hq-table-scroll"><table className="hq-table"><caption>요금제별 전체 가게 현황</caption><thead><tr><th>요금제</th><th>전체 가게</th><th>체험 중</th><th>체험 종료·중단</th><th>체험 중 월 요금 합계</th></tr></thead><tbody>{data.overview.distribution.map((p:any)=><tr key={p.id}><th><button onClick={()=>{setPage(0);setSearch('');setFilters({...defaults,plan:p.id});listRef.current?.scrollIntoView({block:'start'})}}>{p.name} →</button></th><td>{p.count}곳</td><td>{p.trialing}곳</td><td>{p.expired}곳</td><td>{money(p.monthlyQuote)}원</td></tr>)}</tbody></table></div><p className="hq-footnote">수금액·결제 고객 수·갱신율은 결제 기록이 연결된 뒤 집계할 수 있습니다. 현재 금액은 매출이 아닙니다.</p></section>
 <div className="hq-two"><section className="hq-panel"><h2>최근 6개월 새 가게</h2><p>월별 가게 개설 수 · 한국시간 기준</p><div className="hq-bars">{data.overview.months.map((m:any)=><div key={m.month}><b>{m.count}곳</b><div className="hq-bar-track"><span style={{height:(m.count?Math.max(4,m.count/Math.max(1,...data.overview.months.map((x:any)=>x.count))*100):0)+'%'}}/></div><small>{m.month.slice(2).replace('-','.')}</small></div>)}</div><p className="hq-footnote">개설일 기록이 없는 가게 {t.unknownCreatedAt}곳은 신규 집계에서 제외합니다.</p></section><section className="hq-panel"><h2>운영 연결 상태</h2><dl className="hq-service"><div><dt>카드·정기결제</dt><dd>연결 전</dd></div><div><dt>인증·복구 이메일</dt><dd>{data.emailReady?'발송 설정 연결됨':'발송 서비스 연결 필요'}</dd></div><div><dt>전자계약</dt><dd>앱 내 양측 확인·동의 기록</dd></div><div><dt>집계 시각</dt><dd>{time(data.generatedAt)}</dd></div></dl><p className="hq-footnote">이메일 설정이 연결되어도 실제 수신 확인은 별도입니다. 직원 개인 급여·계약 본문은 이 화면에 수집하지 않습니다.</p>{t.dataIssues>0&&<button onClick={()=>attention('data')}>데이터 확인 필요 {t.dataIssues}곳 →</button>}</section></div>
 <section className="hq-panel"><h2>어떤 업종에서 쓰나요?</h2><div className="hq-industries">{data.overview.industries.map((i:any)=><div key={i.name}><span>{i.name}</span><b>{i.count}곳</b></div>)}</div></section><section className="hq-panel" id="hq-customers" ref={listRef} aria-busy={loading}><div className="hq-section-title"><div><h2>고객 가게 관리</h2><p>전체 {data.total}곳 중 조건에 맞는 {data.matched}곳</p></div>{(Object.values(filters).some(Boolean)||search)&&<button onClick={()=>{setPage(0);setSearch('');setFilters(defaults)}}>조건 초기화</button>}</div><form className="hq-filter" onSubmit={e=>{e.preventDefault();filter('q',search)}}><label className="hq-search"><span>가게·지점 이름</span><div><input value={search} onChange={e=>setSearch(e.target.value)} maxLength={100} placeholder="모든 가게에서 검색"/><button type="submit">검색</button></div></label><label><span>요금제</span><select value={filters.plan} onChange={e=>filter('plan',e.target.value)}><option value="">전체 요금제</option>{Object.entries(planNames).map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label><label><span>이용 상태</span><select value={filters.status} onChange={e=>filter('status',e.target.value)}><option value="">전체 상태</option>{Object.entries(statusNames).map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label><label><span>확인할 일</span><select value={filters.attention} onChange={e=>filter('attention',e.target.value)}>{[['','전체'],['all','확인 필요'],['joins','직원 가입 대기'],['corrections','출퇴근 정정'],['trial','체험 종료 예정'],['capacity','직원 한도'],['mail','발송 확인'],['support','본사 확인 중'],['data','데이터 확인']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label><span>사업자 확인</span><select value={filters.biz} onChange={e=>filter('biz',e.target.value)}>{[['','전체'],['확인 전','확인 전'],['수동 확인','수동 확인'],['불일치','불일치']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></form>
 {loading&&<p role="status">조건에 맞는 가게를 확인 중입니다.</p>}<div className="hq-customers">{data.stores.map((s:AdminStore)=><article key={s.id} className="hq-customer"><div className="hq-customer-title"><div><h3>{s.name}</h3><span>{s.industry} · {s.branches.length}개 매장 · 직원 {s.employees}명</span></div><span className={'hq-badge '+(s.status==='trialing'?'is-green':'')}>{statusNames[s.status]}</span></div><div className="hq-customer-meta"><b>{planNames[s.plan]}</b><span>{s.monthlyQuote===null?'기존 이용 조건':`요금안 월 ${money(s.monthlyQuote)}원`}</span><small>{s.daysLeft!==null?`체험 ${s.daysLeft}일 남음`:'자동 결제 없음'}</small></div><div className="hq-flags">{s.pendingJoins>0&&<span>가입 대기 {s.pendingJoins}</span>}{s.pendingCorrections>0&&<span>정정 대기 {s.pendingCorrections}</span>}{s.failedMail>0&&<span>발송 확인 {s.failedMail}</span>}{s.employeeCapacity&&<span>직원 한도 도달</span>}{s.overCapacity&&<span>이용 한도 초과</span>}{s.trialEnding&&<span>체험 종료 예정</span>}{s.dataIssue&&<span>데이터 확인</span>}</div><div className="hq-customer-bottom"><span>본사 · {s.support.status}</span><button className="saas-secondary" disabled={loading} onClick={()=>open(s)}>상세·관리 메모 <ArrowUpRight size={16}/></button></div></article>)}</div>{!loading&&!data.stores.length&&<div className="hq-empty"><Building2 size={30}/><h3>{data.total?'조건에 맞는 가게가 없어요':'아직 가입한 가게가 없어요'}</h3><p>{data.total?'검색어나 선택한 조건을 바꿔 주세요.':'사장님이 가입하고 가게를 만들면 여기에 모입니다.'}</p></div>}<div className="hq-pagination"><button className="saas-secondary" disabled={!data.page||loading} onClick={()=>setPage(data.page-1)}>이전</button><span>{data.page+1} / {Math.max(1,Math.ceil(data.matched/data.pageSize))} 페이지</span><button className="saas-secondary" disabled={(data.page+1)*data.pageSize>=data.matched||loading} onClick={()=>setPage(data.page+1)}>다음</button></div></section></>}
 {selected&&<dialog ref={dialog} className="hq-dialog" aria-labelledby="hq-detail-title" onCancel={e=>{e.preventDefault();if(!busy)setSelected(null)}}><div className="hq-dialog-head"><div><span className="hq-eyebrow">가게 상세 · 본사 내부용</span><h2 id="hq-detail-title">{selected.name}</h2></div><button aria-label="가게 상세 닫기" disabled={busy} onClick={()=>setSelected(null)}><X size={23}/></button></div><p>{planNames[selected.plan]} · {statusNames[selected.status]}<br/>요금안 월 {selected.monthlyQuote===null?'확인 필요':money(selected.monthlyQuote)+'원'} · VAT 포함 · 실제 청구 아님</p><dl className="hq-service"><div><dt>가게 개설</dt><dd>{time(selected.createdAt)}</dd></div><div><dt>최근 기록 변경</dt><dd>{time(selected.updatedAt)}</dd></div>{selected.trialEndsAt&&<div><dt>체험 종료</dt><dd>{time(selected.trialEndsAt)}</dd></div>}</dl><h3>매장별 직원 수</h3>{selected.branches.map((b,i)=><div className="hq-branch" key={i}><span>{b.name}</span><b>{b.employees} / {b.limit}명</b></div>)}<BizCheck store={selected} onDone={async()=>{setSelected(null);setMessage('사업자 확인 상태를 저장했어요.');await load()}}/><form onSubmit={e=>{e.preventDefault();void save()}}><label className="saas-field">관리 상태<select value={status} onChange={e=>setStatus(e.target.value)}>{['미확인','확인 중','처리 완료'].map(s=><option key={s}>{s}</option>)}</select></label><label className="saas-field">본사 메모<textarea maxLength={2000} rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="문의 내용과 다음 확인 사항"/><small>고객 화면에 표시되지 않아요. {note.length} / 2,000자</small></label>{saveError&&<p role="alert" className="saas-error">{saveError}</p>}<div className="hq-dialog-actions"><button className="saas-secondary" type="button" disabled={busy} onClick={()=>setSelected(null)}>닫기</button><button className="saas-primary" disabled={busy}>{busy?'저장 중…':'관리 메모 저장'}</button></div></form><details><summary>상태 변경 이력 ({selected.support.history.length})</summary>{selected.support.history.length?selected.support.history.slice().reverse().map((h:any,i:number)=><p key={i}>{time(h.at)} · {h.status}</p>):<p>변경 이력이 없습니다.</p>}</details></dialog>}
 </main>;
}

/** 작업 012: 사업자 확인 수동 처리 */
function BizCheck({store,onDone}:{store:any,onDone:()=>Promise<void>}){
 const [st,setSt]=useState(store.biz?.status||'확인 전'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 return <section className="hq-biz"><h3>사업자 확인 <small>{store.biz?.status||'확인 전'}{store.biz?.at?` · ${new Date(store.biz.at).toLocaleDateString('ko-KR')}`:''}</small></h3>{store.biz?.reason&&<p className="footnote">최근 사유: {store.biz.reason}</p>}<div className="t-wrapactions"><select aria-label="사업자 확인 상태" value={st} onChange={e=>setSt(e.target.value)}>{['확인 전','수동 확인','불일치'].map(v=><option key={v}>{v}</option>)}</select><input aria-label="처리 사유" maxLength={500} placeholder="예: 사업자등록증 사본 확인" value={reason} onChange={e=>setReason(e.target.value)}/><button type="button" className="saas-secondary" disabled={busy||!reason.trim()} onClick={async()=>{setBusy(true);setErr('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'bizCheck',id:store.id,version:store.version,status:st,reason})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await onDone()}catch(e){setErr((e as Error).message)}finally{setBusy(false)}}}>사유와 함께 저장</button></div>{err&&<p className="saas-error" role="alert">{err}</p>}</section>
}
/** 작업 073: 본사 열람 기록 */
export function HqAccessLog(){
 const [log,setLog]=useState<any[]|null>(null),[open,setOpen]=useState(false);
 return <details className="hq-panel hq-log" onToggle={e=>{const o=(e.target as HTMLDetailsElement).open;setOpen(o);if(o&&!log)fetch('/api/admin?log=1').then(r=>r.json()).then((d:any)=>setLog(d.log||[])).catch(()=>setLog([]))}}><summary>본사 열람 기록 (최근 200건 · 1년 보관)</summary>{open&&(log===null?<p>불러오는 중…</p>:<table className="t-table"><thead><tr><th>시각</th><th>계정</th><th>한 일</th><th>대상</th></tr></thead><tbody>{log.map((l,i)=><tr key={i}><td>{new Date(l.at).toLocaleString('ko-KR')}</td><td>{l.actor}</td><td>{l.action}</td><td>{l.target||(l.detail?.filters&&Object.keys(l.detail.filters).length?JSON.stringify(l.detail.filters):'전체 목록')}</td></tr>)}</tbody></table>)}</details>
}

/** 작업 066: 가격·약관 변경 고지(시행 30일 전) */
function ServiceNoticeAdmin(){
 const [list,setList]=useState<any[]|null>(null),[f,setF]=useState({kind:'가격',title:'',body:'',effectiveAt:''}),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const load=()=>fetch('/api/admin?notices=1').then(r=>r.json()).then((d:any)=>setList(d.notices||[])).catch(()=>setList([]));
 const min=new Date(Date.now()+31*86400000).toISOString().slice(0,10);
 return <details className="hq-panel" onToggle={e=>{if((e.target as HTMLDetailsElement).open&&!list)load()}}><summary><b>가격·약관 변경 고지</b></summary><p className="footnote">시행일 30일 전까지 고지해야 해요. 사장님 화면 맨 위에 보이고, 동의 기록이 남아요.</p>
  <div className="t-wrapactions"><select aria-label="종류" value={f.kind} onChange={e=>setF({...f,kind:e.target.value})}><option>가격</option><option>약관</option></select><input aria-label="제목" placeholder="제목" maxLength={100} value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><input aria-label="시행일" type="date" min={min} value={f.effectiveAt} onChange={e=>setF({...f,effectiveAt:e.target.value})}/></div>
  <textarea aria-label="변경 내용" rows={4} maxLength={3000} style={{width:'100%'}} placeholder="무엇이 어떻게 바뀌는지" value={f.body} onChange={e=>setF({...f,body:e.target.value})}/>
  <button className="saas-secondary" disabled={busy||!f.title.trim()||!f.body.trim()||!f.effectiveAt} onClick={async()=>{setBusy(true);setMsg('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'serviceNotice',...f})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setMsg('고지했어요.');setF({kind:'가격',title:'',body:'',effectiveAt:''});load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}}>고지 등록</button>{msg&&<p role="status">{msg}</p>}
  {list&&<ul>{list.map(n=><li key={n.id}>{n.kind} · {n.title} · 시행 {n.effective_at} · 동의 {n.agreed}명</li>)}</ul>}
 </details>
}
