import {ContractLimits} from './limits-note';
import {DocumentDownload,DocumentStatus} from './document-delivery';
import {useEffect,useRef,useState} from 'react';
const states:Record<string,string>={waiting:'서명 대기 중',signed:'두 분 서명 완료',declined:'직원이 수정 요청',withdrawn:'사장님이 요청 철회'};
const delivery:Record<string,string>={not_ready:'서명 후 사본을 받을 수 있어요',pending:'이메일 발송 준비',sending:'발송 처리 중',accepted:'발송 서비스 접수 · 수령 확인 대기',failed:'발송 실패 · 다시 보내 주세요',setup_required:'이메일 발송 연결 필요',paper_pending:'종이 사본 전달 대기'};
export function ContractsDesk(){
 const [data,setData]=useState<any>(null),[page,setPage]=useState(0),[selected,setSelected]=useState<any>(null),[creating,setCreating]=useState(false),[employeeId,setEmployeeId]=useState(''),[text,setText]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[consent,setConsent]=useState(false),[method,setMethod]=useState('app'),[reason,setReason]=useState(''),[receipt,setReceipt]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[events,setEvents]=useState<any[]>([]),lock=useRef(false);
 async function load(){try{const r=await fetch('/api/contracts?page='+page),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);return d}catch(e){setError(e instanceof Error?e.message:'계약서를 열지 못했어요.')}}useEffect(()=>{load()},[page]);
 function reset(){setName('');setPassword('');setConsent(false);setReason('');setReceipt(false);setError('');setMessage('')}
 async function open(e:any){reset();setCreating(false);setSelected(e);setEvents([]);try{const r=await fetch('/api/contracts?id='+encodeURIComponent(e.id)),d:any=await r.json();if(!r.ok)throw Error(d.error);setSelected(d.envelope);setEvents(d.events);if(!data?.owner){await fetch('/api/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'contract',id:e.id,action:'view'})})}}catch(e){setError(e instanceof Error?e.message:'연결을 확인해 주세요.')}}
 async function action(action:string){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/contracts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:selected?.id,version:selected?.version,documentHash:selected?.document_hash,employeeId,text,name,password,consent,deliveryMethod:method,reason,confirmed:receipt})}),d:any=await r.json();if(!r.ok)throw Error(d.error);const fresh=await load();if(selected){const r=await fetch('/api/contracts?id='+encodeURIComponent(selected.id)),v:any=await r.json();if(r.ok){setSelected(v.envelope);setEvents(v.events)}}if(creating){setCreating(false);setSelected(fresh?.envelopes.find((e:any)=>e.id===d.id)||null)}setPassword('');setConsent(false);setMessage(d.message||'처리했어요. 아래 상태를 확인해 주세요.')}catch(e){setError(e instanceof Error?e.message:'처리하지 못했어요.')}finally{lock.current=false;setBusy(false)}}
 const selectedEmployee=data?.employees.find((e:any)=>e.id===employeeId);
 const signing=creating||selected?.status==='waiting'&&!data?.owner;
 return <main className="saas-account contracts-desk"><a href="/app">← 내 매장으로</a><div className="contract-page-heading"><div><p className="saas-kicker">약속을 함께 확인해요</p><h1>{data?.owner?'전자 근로계약서':'내 전자계약서'}</h1><p>{data?.owner?'계약서 작성 → 사장님 서명 → 직원 서명 → 사본 전달':'내용 확인 → 내 성명으로 서명 → 사본 받기'}</p></div>{data?.owner&&<button className="saas-primary" disabled={busy||!data.canCreate} onClick={()=>{reset();setSelected(null);setCreating(true);setEmployeeId('');setText('')}}>새 계약서 만들기</button>}</div><ContractLimits/>
 {error&&<p className="saas-error" role="alert">{error}</p>}{message&&<p className="saas-success" role="status">{message}</p>}

 {data?.owner&&!data.canCreate&&<p className="notice">새 계약 요청은 베이직 이상에서 사용할 수 있어요. 기존 사본은 계속 볼 수 있어요. <a href="/account">이용권 확인</a></p>}
 {!creating&&!selected&&<><button className="saas-secondary" onClick={load}>상태 새로 확인</button><div className="contract-list">{data?.envelopes.map((e:any)=><button className="contract-list-item" key={e.id} onClick={()=>open(e)}><span><b>{e.document.employeeName}님의 근로계약서</b><small>{e.document.storeName} · {new Date(e.created_at).toLocaleDateString('ko-KR')}</small></span><span>{states[e.status]} →<small><DocumentStatus activity={e.activity}/></small></span></button>)}</div>{data&&!data.envelopes.length&&<section className="auth-card"><h2>아직 받은 계약서가 없어요</h2><p>{data.owner?'직원 가입을 수락한 뒤 새 계약서를 만들어 주세요.':'사장님이 계약서를 보내면 여기에 보여요.'}</p><button className="saas-secondary" onClick={load}>새로 확인하기</button></section>}<div className="t-wrapactions t-gap"><button disabled={page===0||busy} onClick={()=>setPage(page-1)}>이전</button><span>{page+1}페이지</span><button disabled={data?.envelopes.length<20||busy} onClick={()=>setPage(page+1)}>다음</button></div></>}
 {(creating||selected)&&<section className="auth-card"><button className="auth-text-button" disabled={busy} onClick={()=>{setSelected(null);setCreating(false);reset()}}>← 계약서 목록</button>
 {creating?<><h2>1. 직원과 계약 내용을 확인해요</h2><label className="saas-field">직원 선택<select value={employeeId} onChange={e=>{setEmployeeId(e.target.value);setText(data.employees.find((m:any)=>m.id===e.target.value)?.draft||'');reset()}}><option value="">직원을 골라 주세요</option>{data.employees.map((e:any)=><option key={e.id} value={e.id} disabled={!e.linked}>{e.name}{!e.linked?' · 계정 연결 필요':''}</option>)}</select></label>{selectedEmployee&&<><p>대괄호로 남아 있는 빈칸을 모두 채워 주세요. 직원에게 보낼 최종 내용입니다.</p><label className="saas-field">계약서 본문<textarea rows={20} maxLength={30000} value={text} onChange={e=>setText(e.target.value)}/></label><small>내용을 보낸 뒤에는 수정할 수 없어요. 변경하려면 요청을 철회하고 새 계약서를 보내 주세요.</small></>}</>:<><h2>{selected.document.employeeName}님의 계약서</h2><p className="saas-status">{states[selected.status]}</p><pre className="t-document">{selected.document.text}</pre><div className="contract-signature-pair"><div><b>사장님</b><p>{selected.ownerSignature.name} · 서명 완료</p><small>{new Date(selected.ownerSignature.at).toLocaleString('ko-KR')}</small></div><div><b>직원</b><p>{selected.employeeSignature?selected.employeeSignature.name+' · 서명 완료':'확인 기다리는 중'}</p>{selected.completed_at&&<small>{new Date(selected.completed_at).toLocaleString('ko-KR')}</small>}</div></div>{selected.reason&&<p className="notice">사유: {selected.reason}</p>}</>}
 {signing&&(creating?!!selectedEmployee:true)&&<div className="contract-sign-form"><h2>{creating?'2. 사장님이 먼저 서명해요':'내용이 맞으면 서명해 주세요'}</h2><p>성명을 입력하고 동의하면 현재 로그인한 계정으로 전자서명을 기록합니다.</p><label className="saas-field">{creating?'사업주':'직원 본인'} 성명 · {creating?selectedEmployee?.employer:selected.document.employeeName}<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label>{data.native&&<label className="saas-field">현재 비밀번호로 한 번 더 확인<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} maxLength={128}/></label>}
 {!creating&&<p>서명한 계약서는 이 앱에서 확인하고 이미지로 저장할 수 있어요.</p>}
 <label className="saas-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{creating?'사업주로서 계약 내용을 확인했고, 본인 의사로 이 계약서에 전자서명합니다.':'계약 내용을 모두 확인했고, 본인 의사로 이 계약서에 전자서명합니다.'}</span></label><button className="saas-primary" disabled={busy||!consent||!name.trim()||data.native&&!password||creating&&!employeeId} onClick={()=>action(creating?'create':'sign')}>{busy?'안전하게 기록하는 중…':creating?'서명하고 직원에게 확인 요청':'동의하고 전자서명 완료'}</button></div>}
 {selected?.status==='waiting'&&<details className="t-gap"><summary>{data.owner?'이 요청을 철회하고 싶어요':'내용이 달라요 · 수정 요청하기'}</summary><label className="saas-field">사유<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500}/></label><button className="saas-secondary" disabled={busy||!reason.trim()} onClick={()=>action(data.owner?'withdraw':'decline')}>{data.owner?'서명 요청 철회':'서명하지 않고 수정 요청'}</button></details>}
 {selected?.status==='signed'&&<DocumentDownload key={selected.id} kind="contract" id={selected.id} onChange={load}/>}
 {selected&&<details className="t-gap"><summary>문서번호와 처리 기록</summary><p className="contract-hash">문서번호 {selected.id}<br/>SHA-256 {selected.document_hash}</p>{events.map((e:any,i:number)=><p key={i}>{new Date(e.recorded_at).toLocaleString('ko-KR')} · {states[e.status]} · 기록 {e.version}</p>)}<small>계정 확인·성명 입력·동의 시각을 보관하는 앱 전자서명입니다. 제3자 본인확인이나 인증서 서명은 아닙니다.</small></details>}
 </section>}
 </main>;
}
