import {type Team,datePlus} from '../lib/team-model';

const minutes=(v:string)=>Number(v.slice(0,2))*60+Number(v.slice(3));
export function DailySchedule({state,employees,date,onEdit}:{state:Team,employees:Team['employees'],date:string,onEdit:(shift:Team['shifts'][number])=>void}){
 const rows=employees.map(employee=>({employee,segments:state.shifts.filter(s=>s.employeeId===employee.id).flatMap(shift=>{
  const start=minutes(shift.start),end=minutes(shift.end),overnight=end<start;
  if(shift.date===date)return [{shift,start,end:overnight?1440:end,continued:false,overnight}];
  if(overnight&&shift.date===datePlus(date,-1)&&end>0)return [{shift,start:0,end,continued:true,overnight}];
  return [];
 }).sort((a,b)=>a.start-b.start)}));
 return <><div className="simple-instruction"><b>오늘 누가, 몇 시에 일하나요?</b><p>{date} · 근무 예정 직원 {rows.filter(r=>r.segments.length).length}명. 막대를 누르면 근무 시간을 수정할 수 있어요.</p></div><p className="table-scroll-help" id="daily-help">왼쪽은 직원, 위쪽은 시간이에요. 표가 잘리면 옆으로 밀어 보세요. 휴게시간의 위치는 표시하지 않아요.</p><div className="t-tablewrap" tabIndex={0} role="region" aria-label="일간 근무 시간표" aria-describedby="daily-help"><div className="daily-grid"><div className="daily-row daily-head"><strong>직원 / 업무</strong><div className="daily-hours">{Array.from({length:24},(_,h)=><span key={h}>{String(h).padStart(2,'0')}시</span>)}<span className="daily-end">24시</span></div></div>{rows.map(({employee,segments})=><div className="daily-row" key={employee.id}><div className="daily-person"><b>{employee.name}</b><small>{employee.role}</small></div><div className="daily-tracks" style={{height:Math.max(1,segments.length)*64+16}}>{segments.length===0?<span className="daily-empty">등록된 근무 없음</span>:segments.map((seg,i)=><button key={seg.shift.id} className="daily-bar" style={{left:`${seg.start/14.4}%`,width:`${Math.max(seg.end-seg.start,1)/14.4}%`,top:8+i*64}} onClick={()=>onEdit(seg.shift)} aria-label={`${employee.name} ${seg.shift.date} ${seg.shift.start}부터 ${seg.overnight?'다음 날 ':''}${seg.shift.end}까지, 휴게 ${seg.shift.breakMinutes}분, 수정`}><span>{seg.continued?'전날부터 → ':''}{seg.shift.start}–{seg.overnight?'다음 날 ':''}{seg.shift.end}</span><small>휴게 {seg.shift.breakMinutes}분</small></button>)}</div></div>)}</div></div><div className="daily-list"><h2>오늘 근무 시간 한 번 더 보기</h2>{rows.filter(r=>r.segments.length).map(({employee,segments})=><div key={employee.id}><b>{employee.name}</b>{segments.map(seg=><button key={seg.shift.id} onClick={()=>onEdit(seg.shift)}>{seg.continued?'전날 ':''}{seg.shift.start} → {seg.overnight&&!seg.continued?'다음 날 ':''}{seg.shift.end} · 휴게 {seg.shift.breakMinutes}분 · 수정</button>)}</div>)}{!rows.some(r=>r.segments.length)&&<p>등록된 근무가 없어요. 위의 ‘근무 추가’를 눌러 주세요.</p>}</div></>;
}
