import {useState} from 'react';
export function Evidence({leaveId,pending}:{leaveId:string,pending:boolean}){
 const [open,setOpen]=useState(false),[files,setFiles]=useState<any[]>([]),[file,setFile]=useState<File|null>(null),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[remove,setRemove]=useState('');
 const endpoint='/api/evidence?leave='+encodeURIComponent(leaveId);
 const load=async()=>{try{const r=await fetch(endpoint),d:any=await r.json();if(!r.ok)throw Error(d.error);setFiles(d.files)}catch(e){setMessage(String(e instanceof Error?e.message:e))}};
 async function upload(){if(!file||!consent||busy)return;if(file.size>512000){setMessage('파일은 500KB 이하로 선택해 주세요.');return}setBusy(true);setMessage('');try{const bytes=new Uint8Array(await file.arrayBuffer());let text='';for(const b of bytes)text+=String.fromCharCode(b);const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mime:file.type,body:btoa(text),consent})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setFile(null);setConsent(false);setMessage('제출했어요. 신청자와 사장님만 확인할 수 있어요.');await load()}catch(e){setMessage(e instanceof Error?e.message:'제출하지 못했어요.')}finally{setBusy(false)}}
 async function download(id:string){setBusy(true);try{const r=await fetch(endpoint+'&id='+encodeURIComponent(id)),d:any=await r.json();if(!r.ok)throw Error(d.error);const bytes=Uint8Array.from(atob(d.body),(c:string)=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:d.mime})),a=document.createElement('a');a.href=url;a.download='휴가-증빙.'+(d.mime==='application/pdf'?'pdf':d.mime==='image/png'?'png':'jpg');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setMessage(e instanceof Error?e.message:'열지 못했어요.')}finally{setBusy(false)}}
 async function erase(){setBusy(true);try{const r=await fetch(endpoint+'&id='+encodeURIComponent(remove),{method:'DELETE'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setRemove('');setMessage('파일을 삭제했어요.');await load()}catch(e){setMessage(e instanceof Error?e.message:'삭제하지 못했어요.')}finally{setBusy(false)}}
 return <section className="evidence-box"><button type="button" aria-expanded={open} onClick={()=>{if(!open)load();setOpen(!open)}}>진단서·증빙 {open?'접기':'제출 / 확인하기'}</button>{open&&<><p>필요한 증빙만 제출해 주세요. 주민등록번호·주소와 불필요한 진료 내용은 가려 주세요. 이 신청의 직원 본인과 사장님만 볼 수 있어요.</p><p>PDF·JPG·PNG, 파일당 500KB 이하, 신청당 3개. 제출 후 30일 동안 열람할 수 있어요. 열람기한이 지난 파일은 다음 증빙 제출 시 정리되며, 지금 직접 삭제할 수도 있어요.</p>{files.map((f,i)=><div className="evidence-file" key={f.id}><span>증빙 {i+1} · {Math.ceil(f.bytes/1024)}KB · 열람기한 {f.expires_at.slice(0,10)}</span><button type="button" disabled={busy} onClick={()=>download(f.id)}>내려받기</button><button type="button" disabled={busy} onClick={()=>setRemove(f.id)}>삭제</button></div>)}{!files.length&&<p>제출된 파일이 없어요.</p>}{remove&&<div role="alert"><p>이 파일을 삭제하면 되돌릴 수 없어요.</p><button type="button" onClick={()=>setRemove('')}>파일 남겨두기</button><button type="button" disabled={busy} onClick={erase}>삭제하기</button></div>}{pending&&<><label>1. 증빙 파일 고르기<input type="file" accept="application/pdf,image/jpeg,image/png" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setConsent(false);setMessage('')}}/></label><label className="evidence-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>2. 이 파일을 휴가 확인 목적으로 제출하고, 신청자와 사장님이 열람하는 데 동의해요.</label><button type="button" disabled={!file||!consent||busy} onClick={upload}>{busy?'처리 중이에요…':'3. 증빙 제출하기'}</button></>}{message&&<p role="status">{message}</p>}</>}</section>;
}
