import {type Team,calculate,today,kdate,won} from '@/lib/team-model';
import {checkDay} from '@/lib/attendance-check';
export function HomeOverview({state,branch,onPayroll,onAttendance,onSchedule,onEmployees,onRegister,onJoin,children}:{children?:import('react').ReactNode;state:Team;branch:string;onPayroll:()=>void;onAttendance:()=>void;onSchedule:()=>void;onEmployees:()=>void;onRegister:()=>void;onJoin?:()=>void}){
 const employees=state.employees.filter(e=>e.branchId===branch),ids=new Set(employees.map(e=>e.id)),month=today().slice(0,7),run=state.payrollRuns[month+':'+branch];
 const rows=run?.locked?run.rows:calculate(state,month).filter(e=>e.branchId===branch),total=rows.reduce((sum:number,row:any)=>sum+row.net,0);
 const here=state.attendance.filter(a=>ids.has(a.employeeId));
 const attended=new Set(here.filter(a=>kdate(a.start)===today()).map(a=>a.employeeId)).size;
 const working=new Set(here.filter(a=>!a.end).map(a=>a.employeeId)).size;
 const findings=checkDay(today(),state.shifts.filter(x=>ids.has(x.employeeId)),here,((state.settings as any).attendanceTolerance||'normal'));
 if(!employees.length)return <section className="home-start"><img src="/cheokcheoki-welcome.png" alt="" width="88" height="88"/><h2>직원이 직접 신청하면, 사장님은 수락만</h2><p>직원에게 가입 주소를 알려 주세요. 합류 신청을 확인하고 수락하면 우리 가게에 연결돼요.</p><button className="home-main-action" onClick={onJoin||(()=>location.assign('/staff-requests'))}>직원 가입 안내·신청 확인 →</button><p><button onClick={onRegister}>사장님이 직접 직원 입력하기</button></p></section>;
 return <div className="home-overview"><button className="home-schedule-link" onClick={onJoin||(()=>location.assign('/staff-requests'))}>직원 가입 신청 확인 →</button><section className="home-pay-summary" aria-labelledby="home-pay-title"><div className="home-pay-label"><h2 id="home-pay-title">이번 달 {run?.locked?'확정':'예상'} 급여</h2><span>{Number(month.slice(5))}월</span></div><div className="home-pay-amount">{won(total)}<span>원</span></div><p>{run?.locked?'확정된 실수령 합계 · 송금 내역은 아니에요':'입력된 근무·수당·공제 기준 · 검토 전'}</p><div className="home-pay-bottom"><button className="home-main-action" onClick={onPayroll}>급여 자세히 보기 →</button><img src="/cheokcheoki-guide.png" alt="" width="72" height="72"/></div></section><section className="home-today"><button className="home-row-link" onClick={onAttendance}><span>오늘 출근 <strong>{attended}명</strong></span><span>지금 근무 {working}명 <b aria-hidden="true">→</b></span></button><button className="home-schedule-link" onClick={onSchedule}>오늘 근무표 보기 →</button>{findings.length>0&&<button className="home-row-link home-check" onClick={onAttendance}>오늘 확인 권장 <b>{findings.length}건</b> · {[...new Set(findings.map(f=>f.kind))].join('·')} →</button>}</section>{children}</div>;
}
