import {pastedJoinCode} from '../lib/join-code';
import {useRef,useState} from 'react';
import {today} from '../lib/team-model';
export function EmployeeJoinSteps({data,busy,onApply}:{data:any,busy:boolean,onApply:(body:any)=>void}){
 const [step,setStep]=useState(1),[code,setCode]=useState(new URLSearchParams(location.search).get('code')||''),[name,setName]=useState(data.name||''),[phone,setPhone]=useState(''),[address,setAddress]=useState(''),[joined,setJoined]=useState(today()),[preview,setPreview]=useState<any>(null),[confirmed,setConfirmed]=useState(false),[checking,setChecking]=useState(false),[error,setError]=useState('');const lock=useRef(false);
 async function advance(e:React.FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setChecking(true);setError('');try{const r=await fetch('/api/staff-join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'preview',code:pastedJoinCode(code,location.origin),...(step===2?{name,phone,profile:{address,joined,note:''}}:{})})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setPreview(d);setConfirmed(false);setStep(step+1)}catch(e){setError(e instanceof Error?e.message:'다시 확인해 주세요.')}finally{lock.current=false;setChecking(false)}}
 const title=step===1?'어느 가게에서 일하나요?':step===2?'내 정보를 알려주세요':'근로조건을 확인해 주세요';
 return <section className="auth-card join-wizard"><ol className="join-progress" aria-label="직원 가입 순서">{['가게 찾기','내 정보','근로조건 확인'].map((v,i)=><li key={v} aria-current={step===i+1?'step':undefined}><span>{i+1}</span>{v}</li>)}</ol><h2>{title}</h2>
 {preview&&<p><b>{preview.storeName} · {preview.branchName}</b></p>}
 {step<3?<form onSubmit={advance}>{step===1?<><p>사장님이 보내준 8자리 코드나 가입 링크를 붙여넣어 주세요.</p><label className="saas-field">가게 코드<input required value={code} maxLength={512} autoComplete="off" autoCapitalize="characters" spellCheck={false} onChange={e=>setCode(e.target.value)} placeholder="예: ABCD 2345 또는 가입 링크"/></label></>:<><label className="saas-field">이름<input autoComplete="name" required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label className="saas-field">연락처<input autoComplete="tel" type="tel" required pattern="[0-9+() -]{8,30}" maxLength={30} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="010-0000-0000"/></label><label className="saas-field">이메일<input type="email" value={data.email||''} readOnly/></label><label className="saas-field">주소<input autoComplete="street-address" required maxLength={300} value={address} onChange={e=>setAddress(e.target.value)} placeholder="근로계약서에 쓸 주소"/></label><label className="saas-field">일하기로 한 첫날<input type="date" required value={joined} onInput={e=>setJoined(e.currentTarget.value)} onChange={e=>setJoined(e.target.value)}/></label></>}
 {error&&<p role="alert" className="saas-error">{error}</p>}<button className="saas-primary" disabled={checking||busy}>{checking?'확인하고 있어요…':step===1?'우리 가게 확인하기':'입력한 정보로 다음 단계'}</button></form>:<><dl className="join-summary"><div><dt>이름 · 연락처</dt><dd>{name} · {phone}</dd></div><div><dt>주소</dt><dd>{address}</dd></div><div><dt>첫 근무일</dt><dd>{joined}</dd></div></dl>{preview.contractText?<><p>사장님이 설정한 조건이에요. 다른 내용이 있으면 신청 전에 사장님께 말씀해 주세요.</p><pre className="join-contract" tabIndex={0} aria-label="확인할 근로계약 초안">{preview.contractText}</pre><label className="saas-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>내 정보와 근로조건을 읽고 확인했어요.</span></label><p className="footnote">이 단계는 내용 확인이에요. 계약 서명과 사본 교부는 별도로 진행합니다.</p></>:<div className="notice"><b>계약 내용은 사장님이 준비 중이에요.</b><p>가입 신청을 먼저 보낼 수 있어요. 근로계약서는 사장님 5 이상에서 별도로 작성·확인합니다.</p></div>}
 <p>이름·연락처·주소·첫 근무일과 확인한 계약 내용을 해당 가게 사장님께 전달합니다.</p><button className="saas-primary" disabled={busy||(!!preview.terms&&!confirmed)} onClick={()=>onApply({action:'apply',code:pastedJoinCode(code,location.origin),name,phone,profile:{address,joined,note:''},termsRevision:preview.terms?.revision,confirmed})}>{busy?'신청을 보내고 있어요…':'사장님께 가입 신청 보내기'}</button></>}
 {step>1&&<button className="saas-secondary" disabled={checking||busy} onClick={()=>{setStep(step-1);setError('')}}>← 이전 단계로</button>}
 </section>;
}

export function JoinTermsEditor({branch,initial,enabled,busy,onSave}:{branch:string,initial:any,enabled:boolean,busy:boolean,onSave:(body:any)=>void}){
 const [f,setF]=useState<any>(initial?.fields||{employer:'',workplace:'',duties:'',workDays:'',start:'09:00',end:'18:00',breakMinutes:60,weeklyHours:40,wage:0,payType:'시급',employment:'단시간',endDate:'',payDay:10,holiday:'',leave:'관계 법령 및 사업장 적용 기준에 따름',additional:''});
 const update=(key:string,value:any)=>setF((old:any)=>({...old,[key]:value}));
 return <details className="auth-card t-gap"><summary><b>직원이 가입할 때 확인할 근로조건 {initial?'수정':'설정'}</b></summary>{!enabled?<p>근로계약서 작성과 가입 시 조건 확인은 <a href="/account">사장님 5부터</a> 이용할 수 있어요.</p>:<form className="t-gap" onSubmit={e=>{e.preventDefault();onSave({action:'terms',branchId:branch,fields:f})}}><p>이 매장에 새로 신청하는 직원에게 보여줄 조건이에요. 직원별로 다른 조건은 수락 전에 확인해 주세요.</p><div className="join-form-grid">
 {([['employer','사업주 이름',100],['workplace','근무장소',300],['duties','하는 일',300],['workDays','근무요일',200],['holiday','휴일',300],['leave','휴가',300]] as const).map(([k,label,max])=><label className="saas-field" key={k}>{label}<input required maxLength={max} value={f[k]} onChange={e=>update(k,e.target.value)}/></label>)}
 <label className="saas-field">계약 형태<select value={f.employment} onChange={e=>update('employment',e.target.value)}>{['기간의 정함 없음','기간제','단시간','일용'].map(v=><option key={v}>{v}</option>)}</select></label>{f.employment==='기간제'&&<label className="saas-field">계약 종료일<input type="date" required value={f.endDate||''} onInput={e=>update('endDate',e.currentTarget.value)} onChange={e=>update('endDate',e.target.value)}/></label>}<label className="saas-field">임금 기준<select value={f.payType} onChange={e=>update('payType',e.target.value)}>{['시급','월급','일급'].map(v=><option key={v}>{v}</option>)}</select></label>
 {([['start','근무 시작'],['end','근무 종료']] as const).map(([k,label])=><label className="saas-field" key={k}>{label}<input type="time" required value={f[k]} onInput={e=>update(k,e.currentTarget.value)} onChange={e=>update(k,e.target.value)}/></label>)}
 {([['wage','임금 (원)',1,100000000],['weeklyHours','주 근무시간',1,80],['breakMinutes','휴게시간 (분)',0,720],['payDay','매월 급여일',1,31]] as const).map(([k,label,min,max])=><label className="saas-field" key={k}>{label}<input type="number" required min={min} max={max} value={f[k]} onChange={e=>update(k,Number(e.target.value))}/></label>)}
 </div><label className="saas-field">추가로 약속한 내용 (선택)<textarea maxLength={4000} value={f.additional} onChange={e=>update('additional',e.target.value)}/></label><p className="footnote">표준서식 참고 초안으로 보여줍니다. 서명 완료 처리는 하지 않아요. 조건 변경 전에 들어온 신청은 새 조건을 다시 확인해야 합니다.</p><button className="saas-primary" disabled={busy}>{busy?'저장 중…':'가입용 근로조건 저장'}</button></form>}</details>;
}
