import {useEffect,useState} from 'react';
const localTime=(value:string|null)=>value?new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'아직 퇴근 전';
export function ManagerDesk(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [shift,setShift]=useState({employeeId:'',date:'',start:'09:00',end:'18:00',breakMinutes:60}),[title,setTitle]=useState(''),[body,setBody]=useState(''),[reason,setReason]=useState<Record<string,string>>({});
 async function load(){try{const r=await fetch('/api/manager');const d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('')}catch(e){setError(e instanceof Error?e.message:'불러오지 못했어요.')}}useEffect(()=>{load()},[]);
 async function post(b:any){if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/manager',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...b,version:data.version})});const d:any=await r.json();if(!r.ok)throw Error(d.error);if(b.action==='postNotice'){setTitle('');setBody('')}setMessage('처리했어요. 사장님도 변경 기록을 확인할 수 있어요.');await load()}catch(e){setError(e instanceof Error?e.message:'처리하지 못했어요.')}finally{setBusy(false)}}
 return <main className="saas-account"><a href="/app">← 내 직원 화면</a><h1>매니저 업무</h1><p>{data?.branchName} · 사장님이 맡긴 업무만 처리할 수 있어요.</p><button disabled={busy} onClick={load}>새로 확인</button>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{data&&<>{!data.permissions.length&&<p>아직 위임받은 업무가 없어요. 사장님께 권한을 요청하세요.</p>}{data.permissions.includes('schedule')&&<section className="auth-card t-gap"><h2>근무표 등록</h2><form onSubmit={e=>{e.preventDefault();post({action:'saveShift',shift})}}><label className="saas-field">직원<select required value={shift.employeeId} onChange={e=>setShift({...shift,employeeId:e.target.value})}><option value="">선택해 주세요</option>{data.employees.map((e:any)=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label className="saas-field">근무 날짜<input required type="date" value={shift.date} onInput={e=>setShift({...shift,date:e.currentTarget.value})} onChange={e=>setShift({...shift,date:e.target.value})}/></label>{(['start','end'] as const).map((k,i)=><label className="saas-field" key={k}>{i?'퇴근':'출근'}<input required type="time" value={shift[k]} onInput={e=>setShift({...shift,[k]:e.currentTarget.value})} onChange={e=>setShift({...shift,[k]:e.target.value})}/></label>)}<label className="saas-field">휴게 (분)<input required type="number" min={0} max={720} value={shift.breakMinutes} onChange={e=>setShift({...shift,breakMinutes:Number(e.target.value)})}/></label><button className="saas-primary" disabled={busy}>근무 등록</button></form><details className="t-gap"><summary>등록된 근무 {data.shifts.length}건 보기</summary>{data.shifts.slice().sort((a:any,b:any)=>a.date.localeCompare(b.date)).map((s:any)=><p key={s.id}>{s.date} · {data.employees.find((e:any)=>e.id===s.employeeId)?.name} · {s.start}–{s.end}</p>)}</details></section>}
 {data.permissions.includes('attendance')&&<section className="auth-card t-gap"><h2>출퇴근 수정 요청 {data.corrections.length}건</h2>{data.corrections.map((r:any)=><article className="notice t-gap" key={r.id}><h3>{data.employees.find((e:any)=>e.id===r.before.employeeId)?.name}</h3><p>{r.reason}</p><div className="t-gap">{(['before','after'] as const).map((key)=><section key={key} aria-label={key==='before'?'수정 전 기록':'수정 후 기록'}><h4>{key==='before'?'수정 전':'수정 후'}</h4><p>출근: {localTime(r[key].start)}<br/>퇴근: {localTime(r[key].end)}<br/>휴게: {r[key].breakMinutes}분{r[key].breakStart?' · 휴게 중 (시작 '+localTime(r[key].breakStart)+')':''}</p></section>)}</div><div className="t-wrapactions"><button disabled={busy} onClick={()=>post({action:'reviewCorrection',id:r.id,approve:true})}>수정 승인</button><button disabled={busy} onClick={()=>post({action:'reviewCorrection',id:r.id,approve:false})}>반려</button></div></article>)}{!data.corrections.length&&<p>확인할 요청이 없어요. 본인 요청은 사장님이 확인합니다.</p>}</section>}
 {data.permissions.includes('leave')&&<section className="auth-card t-gap"><h2>휴가 신청 {data.leaves.length}건</h2>{data.leaves.map((l:any)=><article className="notice t-gap" key={l.id}><h3>{l.name} · {l.kind}</h3><p>{l.start} ~ {l.end} · {l.days}일 · {l.reason}</p><label className="saas-field">처리 사유<input maxLength={500} value={reason[l.id]||''} onChange={e=>setReason({...reason,[l.id]:e.target.value})}/></label><div className="t-wrapactions"><button disabled={busy||!reason[l.id]?.trim()} onClick={()=>post({action:'reviewLeave',id:l.id,approve:true,comment:reason[l.id]})}>휴가 승인</button><button disabled={busy||!reason[l.id]?.trim()} onClick={()=>post({action:'reviewLeave',id:l.id,approve:false,comment:reason[l.id]})}>반려</button></div></article>)}{!data.leaves.length&&<p>확인할 신청이 없어요. 본인 휴가는 사장님이 확인합니다.</p>}</section>}
 {data.permissions.includes('notices')&&<form className="auth-card t-gap" onSubmit={e=>{e.preventDefault();post({action:'postNotice',title,body})}}><h2>우리 지점 공지 쓰기</h2><label className="saas-field">제목<input required maxLength={100} value={title} onInput={e=>setTitle(e.currentTarget.value)} onChange={e=>setTitle(e.target.value)}/></label><label className="saas-field">내용<textarea required maxLength={3000} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="saas-primary" disabled={busy}>공지 등록</button></form>}<p>요금제·다른 매장·권한 부여·급여 확정·계약 체결은 사장님이 관리합니다.</p></>}</main>;
}
