import {displayJoinCode,joinPath} from '../lib/join-code';
import {EmployeeJoinSteps,JoinTermsEditor} from './join-steps';
import {CapacityDialog} from './capacity-dialog';
import {useEffect,useState} from 'react';
import {ratesFor} from '../lib/pay-rules';
export function StaffJoin({owner=false,returnTo="/app"}:{owner?:boolean,returnTo?:string}){
 const [limitMessage,setLimitMessage]=useState('');
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [code,setCode]=useState(new URLSearchParams(location.search).get('code')||''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[branch,setBranch]=useState(''),[links,setLinks]=useState<Record<string,string>>({}),[pay,setPay]=useState<Record<string,{payType:string,wage:string}>>({});
 const load=async()=>{try{const r=await fetch('/api/staff-join');const d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setBranch(v=>v||d.branches?.[0]?.id||'');setError('')}catch(e){setError(String(e instanceof Error?e.message:e))}};
 useEffect(()=>{load()},[]);
 const post=async(body:any)=>{if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/staff-join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,version:data?.version})});const d:any=await r.json();if(!r.ok){if(d.code==='CAPACITY_EXCEEDED')setLimitMessage(d.error);throw Error(d.error)}setMessage(body.action==='terms'?'직원이 확인할 근로조건을 저장했어요.':body.action==='withdraw'?'신청을 취소했어요. 올바른 가게 코드로 다시 신청할 수 있어요.':body.action==='apply'?'신청을 보냈어요. 사장님이 확인하면 직원 화면을 사용할 수 있어요.':body.action==='code'?'직원에게 아래 가입 주소를 알려 주세요.':'신청을 처리했어요.');await load()}catch(e){setError(e instanceof Error?e.message:'다시 시도해 주세요.')}finally{setBusy(false)}};
 async function copyValue(value:string,label:string){try{await navigator.clipboard.writeText(value);setMessage(label+'를 복사했어요. 직원에게 붙여넣어 알려 주세요.')}catch{setError('아래 코드나 링크를 길게 눌러 복사해 주세요.')}}
 const pending=data?.requests?.some((a:any)=>a.status==='pending');
 useEffect(()=>{if(!pending)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},30000);return()=>clearInterval(timer)},[pending]);
 const joinCode=data?.codes?.find((x:any)=>x.branchId===branch)?.code,joinUrl=joinCode?location.origin+joinPath(joinCode):'';
 return <main className="saas-account"><CapacityDialog message={limitMessage} onClose={()=>setLimitMessage('')}/><a className="saas-back" href={owner?'/app':'/start'}>← {owner?'우리 가게':'시작 화면'}</a><h1>{owner?'직원 가입 신청':'직원으로 시작하기'}</h1><p>{owner?'직원이 직접 신청하면 사장님이 확인하고 수락해요.':'본인 계정으로 가입하고, 일하는 가게에 합류를 신청해요.'}</p>{error&&<p role="alert" className="saas-error">{error}</p>}{message&&!data?.connected&&<p role="status" className="saas-success">{message}</p>}{!data?<button onClick={load}>다시 불러오기</button>:owner&&!data.owner?<p>사장님 계정으로 확인해 주세요.</p>:owner?<>
 <section className="auth-card"><h2>직원을 우리 가게로 연결하기</h2><p>링크 하나만 보내면 돼요. 직원이 신청하면 여기서 수락해 주세요.</p>{data.branches.length>1&&<label className="saas-field">매장<select value={branch} onChange={e=>setBranch(e.target.value)}>{data.branches.map((b:any)=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label>}{joinCode?<><div className="join-code-card"><span>우리 가게 코드</span><strong>{displayJoinCode(joinCode)}</strong><button type="button" className="saas-secondary" onClick={()=>copyValue(joinCode,'가게 코드')}>코드 복사</button></div><label className="saas-field">직원 가입 링크<input readOnly value={joinUrl} onFocus={e=>e.target.select()}/></label>{typeof navigator!=='undefined'&&'share' in navigator&&<button type="button" className="saas-primary" onClick={async()=>{try{await navigator.share({title:'우리 가게 직원 가입',text:'척척사장봇에서 우리 가게 직원으로 가입해 주세요. 링크를 누르면 가게 코드가 자동으로 들어가요.',url:joinUrl})}catch(e){if((e as Error)?.name!=='AbortError')copyValue(joinUrl,'가입 링크')}}}>카톡·문자로 보내기</button>}<button type="button" className={typeof navigator!=='undefined'&&'share' in navigator?'saas-secondary':'saas-primary'} onClick={()=>copyValue(joinUrl,'가입 링크')}>가입 링크 복사</button><small>링크로 들어오면 코드가 자동으로 입력돼요. 사장님이 수락해야 내 직원 화면을 열 수 있어요.</small>{joinCode.length!==8&&<button className="saas-secondary" disabled={busy} onClick={()=>post({action:'code',branchId:branch})}>8자리 코드로 간편하게 바꾸기</button>}{(()=>{const c=data.codes.find((x:any)=>x.branchId===branch)||{},expired=c.expiresAt&&c.expiresAt<new Date().toISOString();return <div className="join-manage"><p className={c.paused||expired?'saas-error':''}>{c.paused?'지금 가입 신청을 받지 않아요(멈춤).':expired?'가입 링크 기간이 끝났어요.':c.expiresAt?`가입 링크는 ${new Date(c.expiresAt).toLocaleDateString('ko-KR')}까지 쓸 수 있어요.`:'가입 링크 기간 제한 없음'}</p><div className="t-wrapactions"><label className="saas-field">기간<select disabled={busy} value="" onChange={e=>e.target.value&&post({action:'code',branchId:branch,days:Number(e.target.value)})}><option value="">바꾸기…</option><option value="7">오늘부터 7일</option><option value="30">오늘부터 30일</option><option value="0">제한 없음</option></select></label><button className="saas-secondary" disabled={busy} onClick={()=>post({action:'code',branchId:branch,paused:!c.paused})}>{c.paused?'가입 신청 다시 받기':'가입 신청 멈추기'}</button><button className="saas-secondary" disabled={busy} onClick={()=>{if(confirm('새 코드로 바꾸면 지금 링크와 코드는 바로 쓸 수 없어요. 바꿀까요?'))post({action:'code',branchId:branch,renew:true})}}>새 코드로 바꾸기</button></div></div>})()}</>:<button className="saas-primary" disabled={busy} onClick={()=>post({action:'code',branchId:branch})}>가게 코드·가입 링크 만들기</button>}</section>
 <JoinTermsEditor key={branch+':'+data.terms?.find((t:any)=>t.branchId===branch)?.revision} branch={branch} initial={data.terms?.find((t:any)=>t.branchId===branch)} enabled={data.contractsEnabled} busy={busy} onSave={post}/><section className="auth-card t-gap"><h2>수락할 신청 {data.requests.length}건</h2><button disabled={busy} onClick={load}>새 신청 확인</button>{data.requests.length===0&&<p>아직 신청이 없어요. 직원이 직접 신청하면 여기에 표시됩니다.</p>}{data.requests.map((a:any)=><article className="notice t-gap" key={a.id}><h3>{a.name}</h3><p>{data.branches.find((b:any)=>b.id===a.branchId)?.name} · {a.email} · {a.phone}</p>{a.emailVerified===false&&<small>이메일 소유 확인 전 · 실제 직원인지 직접 확인하고 수락해 주세요.</small>}{a.profile&&<dl className="join-summary"><div><dt>주소</dt><dd>{a.profile.address}</dd></div><div><dt>첫 근무일</dt><dd>{a.profile.joined}</dd></div>{a.profile.note&&<div><dt>직원이 전한 말</dt><dd>{a.profile.note}</dd></div>}</dl>}{a.contractText&&<details><summary>직원이 확인한 근로계약 내용 보기</summary><pre className="join-contract" tabIndex={0}>{a.contractText}</pre><p>내용 확인: {new Date(a.confirmedAt).toLocaleString('ko-KR')} · 전자서명 아님</p></details>}<label className="saas-field">등록 방법<select value={links[a.id]||''} onChange={e=>setLinks({...links,[a.id]:e.target.value})}><option value="">새 직원으로 등록</option>{data.employees.filter((e:any)=>e.branchId===a.branchId&&e.email.toLowerCase()===a.email&&!data.linkedIds.includes(e.id)).map((e:any)=><option value={e.id} key={e.id}>기존 직원 {e.name}과 연결</option>)}</select></label>{!a.contractText&&!links[a.id]&&(()=>{const p=pay[a.id]||{payType:'시급',wage:''},min=ratesFor(new Date().getFullYear()).minimumWage,low=p.payType==='시급'&&Number(p.wage)>0&&Number(p.wage)<min;return <fieldset className="join-pay"><legend>임금 정하기 (필수)</legend><p>가입 근로조건 없이 신청했어요. 급여 계산에 쓸 임금을 정해 주세요. 나머지 근로조건은 직원 관리에서 채울 수 있어요.</p><label className="saas-field">임금 기준<select value={p.payType} onChange={e=>setPay({...pay,[a.id]:{...p,payType:e.target.value}})}><option>시급</option><option>월급</option><option>일급</option></select></label><label className="saas-field">임금 (원)<input type="number" inputMode="numeric" min={1} required value={p.wage} placeholder={p.payType==='시급'?String(min):''} onChange={e=>setPay({...pay,[a.id]:{...p,wage:e.target.value}})}/></label>{low&&<small className="t-warn" role="alert">{new Date().getFullYear()}년 최저시급 {min.toLocaleString('ko-KR')}원보다 낮아요. 다시 확인해 주세요.</small>}</fieldset>})()}<p>수락하면 본인 출퇴근·급여·계약 화면에 접근할 수 있어요. 확인한 계약이 있으면 그 조건을 직원 정보에 반영합니다. 계약 서명은 별도입니다.</p><div className="t-wrapactions"><button className="saas-primary" disabled={busy} onClick={()=>post({action:'review',id:a.id,approve:true,employeeId:links[a.id]||undefined,...(!a.contractText&&!links[a.id]?{payType:(pay[a.id]||{payType:'시급'}).payType,wage:Number(pay[a.id]?.wage)||0}:{})})}>수락하기</button><button className="saas-secondary" disabled={busy} onClick={()=>post({action:'review',id:a.id,approve:false})}>반려하기</button></div></article>)}</section><p><a href="/app?screen=employees">사장님이 직접 직원 입력하기 →</a></p>
 </>:data.owner?<p>현재 사장님 계정입니다. 직원은 본인 계정으로 신청해야 해요. <a href="/staff-requests">직원 가입 신청 관리 →</a></p>:data.connected?<section className="auth-card"><h2>가게에 연결됐어요.</h2><a className="saas-primary" href={returnTo}>내 직원 화면 열기 →</a></section>:<>
 {pending?<section className="auth-card"><h2>사장님의 승인을 기다리고 있어요</h2><p>가입 신청을 보냈어요. 사장님이 확인하고 수락하면 출퇴근과 내 기록을 이용할 수 있어요.</p><small>이 화면에서 30초마다 승인 여부를 확인해요.</small><button className="saas-primary" disabled={busy} onClick={load}>사장님이 수락했는지 확인하기</button></section>:<EmployeeJoinSteps data={data} busy={busy} onApply={post}/>}
 <section className="auth-card t-gap"><h2>내 신청 상태</h2>{data.requests.length===0?<p>아직 보낸 신청이 없어요.</p>:data.requests.map((a:any)=><div className="notice t-gap" key={a.id}>{a.storeName} · {a.branchName} — <b>{a.status==='pending'?'사장님 확인 기다리는 중':a.status==='approved'?'수락 완료':a.status==='withdrawn'?'신청 취소됨':'반려됨 · 가게 코드를 확인 후 다시 신청하세요'}</b>{a.contractText&&<details><summary>내가 확인한 근로계약 보기</summary><pre className="join-contract" tabIndex={0}>{a.contractText}</pre></details>}{a.status==='pending'&&<button className="saas-secondary" disabled={busy} onClick={()=>post({action:'withdraw',id:a.id})}>이 가게 합류 신청 취소</button>}</div>)}<button disabled={busy} onClick={load}>수락 여부 새로 확인</button></section></> }</main>;
}

