'use client';
import {useState} from 'react';
import {type Team,calculate,worked,kdate,won,today} from '../lib/team-model';
import {planLimits,hasFeature} from '../lib/plans';
import {Btn,Field,Badge,saveFile} from './team-ui';
import QRCode from 'qrcode';
export function StoreComparison({state,plan,onSave,onOpen,onIssue,demo,busy}:{state:Team,plan:any,onSave:(s:Team)=>Promise<boolean>,onOpen:(id:string)=>void,onIssue:(id:string)=>void,demo:boolean,busy:boolean}){
 const [month,setMonth]=useState(today().slice(0,7)),[name,setName]=useState(''),[message,setMessage]=useState(''),[qr,setQr]=useState(''),[qrName,setQrName]=useState('');
 const limits=planLimits(plan),compare=demo||hasFeature(plan,'comparison');
 const pay=calculate(state,month),rows=state.branches.map(b=>{const es=state.employees.filter(e=>e.branchId===b.id),ids=new Set(es.map(e=>e.id)),att=state.attendance.filter(a=>ids.has(a.employeeId)&&kdate(a.start).startsWith(month));return {...b,employees:es.filter(e=>e.status!=='퇴사').length,hours:att.reduce((n,a)=>n+worked(a),0),cost:pay.filter(r=>ids.has(r.employeeId)).reduce((n,r)=>n+r.gross,0),missing:att.filter(a=>!a.end).length}});
 async function add(){if(!name.trim()||busy)return;setMessage('');if(state.branches.length>=limits.branches){setMessage('현재 요금제의 매장 수를 모두 사용했어요. 계정·요금제에서 매장 수를 늘려 주세요.');return}if(await onSave({...state,branches:[...state.branches,{id:crypto.randomUUID(),name:name.trim(),address:''}]})){setName('');setMessage('새 매장을 만들었어요. 직원부터 등록해 주세요.')}}
 async function issue(b:{id:string,name:string}){if(!demo){onIssue(b.id);return}setQr(await QRCode.toDataURL(location.origin+(demo?'/demo?role=employee&branch=':'/app?branch=')+encodeURIComponent(b.id)+'#attendance',{width:720,margin:3}));setQrName(b.name)}
 return <><div className="simple-instruction"><b>가게가 여러 곳이어도, 여기서 한눈에.</b><p>가게를 누르면 그 매장의 직원과 근무표로 이동해요.</p></div><div className="store-cards">{state.branches.map(b=><article className="panel t-panelbody" key={b.id}><Badge>우리 매장</Badge><h2>{b.name}</h2><p>직원 {rows.find(r=>r.id===b.id)?.employees}명 / {limits.employees}명</p><div className="actions"><Btn primary onClick={()=>onOpen(b.id)}>이 매장 열기 →</Btn><Btn onClick={()=>issue(b)}>매장 출퇴근 QR</Btn></div></article>)}</div><section className="panel t-panelbody t-gap"><h2>매장 추가하기</h2><p>현재 {state.branches.length}곳 / 이용 가능 {limits.branches}곳</p><div className="t-inline"><input aria-label="새 매장 이름" placeholder="예: 시장점" maxLength={80} value={name} onInput={e=>setName(e.currentTarget.value)} onChange={e=>setName(e.target.value)}/><Btn disabled={busy||!name.trim()} onClick={add}>매장 추가</Btn><a href="/account">요금제·매장 수 변경 →</a></div>{message&&<p role="status">{message}</p>}</section>{compare?<section className="panel t-gap"><div className="panel-heading"><h2>매장별 비교</h2><Field label="비교할 달"><input type="month" value={month} onInput={e=>setMonth(e.currentTarget.value)} onChange={e=>setMonth(e.target.value)}/></Field></div><p id="store-table-help" className="table-scroll-help">표가 잘려 보이면 옆으로 밀어 보세요. 키보드는 표를 선택한 뒤 방향키로 이동해요.</p><div className="t-tablewrap" role="region" aria-label="매장별 비교 표" aria-describedby="store-table-help" tabIndex={0}><table className="t-table"><thead><tr>{['매장','직원','실근무 시간','지급액 합계','퇴근 확인','바로가기'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td>{r.employees}명</td><td>{r.hours.toFixed(1)}시간</td><td>{won(r.cost)}원</td><td>{r.missing}건</td><td><Btn onClick={()=>onOpen(r.id)}>매장 열기</Btn></td></tr>)}</tbody></table></div><p className="t-panelbody">기록된 근무와 입력 수당의 합계입니다. 매출·이익을 나타내지 않으며, 세금·보험료·법정수당 전체 자동 계산은 포함하지 않습니다.</p></section>:<section className="panel t-panelbody t-gap"><h2>매장을 늘릴 계획이 있나요?</h2><p>여러 매장 요금제에서는 매장별 직원 수, 근무시간, 인건비를 나란히 비교해요.</p><a href="/account">여러 매장 요금제 보기 →</a></section>}{qr&&<section className="panel t-panelbody t-gap"><h2>{qrName} · 출근용 QR</h2><img src={qr} width={240} height={240} alt={qrName+' 출근 화면 접속 QR'}/><p><b>휴대폰 카메라로 찍으세요.</b><br/>직원이 가입 후 가게 합류를 신청하면 사장님이 수락해요. 출퇴근은 본인 계정으로 로그인해 기록해요.<br/>체험용 QR입니다. 실제 매장은 새 출퇴근 QR을 붙여 두고 직원이 출근·퇴근할 때 확인해요.</p><Btn onClick={()=>{const a=document.createElement('a');a.href=qr;a.download=qrName+'-출근QR.png';a.click()}}>QR 이미지 저장</Btn></section>}</>;
}
