import {useEffect,useRef,useState} from 'react';
export function VerifyEmail(){
 const token=new URLSearchParams(location.hash.slice(1)).get('token'),lock=useRef(false);
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[done,setDone]=useState(false);
 const next=new URLSearchParams(location.search).get('next')==='/contracts'?'/contracts':'/app';
 async function load(){try{const r=await fetch('/api/auth');if(!r.ok)throw Error();setData(await r.json())}catch{setError('연결을 확인하고 새로고침해 주세요.')}}useEffect(()=>{load()},[]);
 async function act(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:token?'verifyEmail':'sendVerification',token})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message||'이메일 확인을 마쳤어요.');if(token||d.verified){setDone(true);history.replaceState(null,'','/verify-email')}await load()}catch(e){setError(e instanceof Error?e.message:'다시 시도해 주세요.')}finally{lock.current=false;setBusy(false)}}
 return <main className="native-auth-wrap"><section className="auth-card native-auth"><img src="/cheokcheoki-welcome.png" alt="이메일을 안내하는 척척이" width="64" height="64"/><span className="saas-kicker">내 계정 확인</span><h1>{done||data?.verified?'이메일 확인 완료':'내 이메일, 한 번만 확인해요'}</h1><p>인증메일의 주소를 누르고 확인하면 끝이에요. 계약서 서명과 내 계정 보호에 사용해요.</p>{data?.email&&<b>{data.email}</b>}{error&&<p role="alert" className="saas-error">{error}</p>}{message&&<p role="status" className="saas-success">{message}</p>}{done||data?.verified?<a className="saas-primary" href={next}>내 화면으로 계속하기 →</a>:token?<><p>본인이 가입한 이메일이 맞다면 아래 버튼을 눌러 주세요.</p><button className="saas-primary" disabled={busy} onClick={act}>{busy?'확인 중…':'이 이메일 확인하기'}</button></>:data?.authenticated?<><button className="saas-primary" disabled={busy||!data.mailReady} onClick={act}>{busy?'보내는 중…':message?'인증메일 다시 받기':'인증메일 받기'}</button>{!data.mailReady&&<p className="notice">운영자가 발신 도메인을 연결하면 이용할 수 있어요. 입력한 정보는 그대로 남아 있어요.</p>}<small>메일이 안 보이면 스팸함도 확인해 주세요. 인증 주소는 30분 동안 사용할 수 있어요.</small></>:<a className="saas-primary" href="/login">로그인하고 인증메일 받기</a>}<a href={next}>내 화면으로 돌아가기</a></section></main>;
}
