import {z} from 'zod';
const id=z.string().min(1).max(80),text=z.string().trim().min(1).max(100),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),money=z.number().int().min(0).max(100000000);
export const employeeSchema=z.object({id,name:text,role:z.enum(['홀','주방','매니저']),type:z.enum(['파트타임','정직원']),wage:z.number().int().min(1).max(1000000),phone:z.string().max(30),joined:date,income:z.enum(['미검토','근로소득','사업소득']),insurance:z.enum(['확인 필요','가입','미가입']),contract:z.enum(['작성 전','검토 중','서명 완료']),contractText:z.string().max(15000)});
export const shiftSchema=z.object({id,employeeId:id,date,start:time,end:time,breakMinutes:z.number().int().min(0).max(720)}).refine(s=>duration(s.start,s.end,s.breakMinutes)>0,{message:'휴게시간은 근무시간보다 짧아야 합니다.'});
export const attendanceSchema=z.object({id,employeeId:id,start:z.string().datetime(),end:z.string().datetime().nullable(),breakMinutes:z.number().int().min(0).max(720),breakStart:z.string().datetime().nullable()}).refine(s=>!s.end || (new Date(s.end)>new Date(s.start)&&((+new Date(s.end)-+new Date(s.start))/60000>s.breakMinutes)),{message:'퇴근시간과 휴게시간을 확인해 주세요.'});
export const reservationSchema=z.object({id,name:text,date,time,people:z.number().int().min(1).max(100),table:z.enum(['1번','2번','3번','4번','단체석']),phone:z.string().max(30),note:z.string().max(1000),status:z.enum(['예약 확정','방문 완료','취소'])});
export const purchaseSchema=z.object({id,name:text,vendor:text,date,quantity:z.number().positive().max(100000),unit:z.enum(['kg','개','박스','L']),price:money,category:z.enum(['식재료','음료','소모품'])});
export const stateSchema=z.object({store:z.object({name:text,branch:text}),employees:z.array(employeeSchema).max(100),shifts:z.array(shiftSchema).max(2000),attendance:z.array(attendanceSchema).max(5000),reservations:z.array(reservationSchema).max(3000),purchases:z.array(purchaseSchema).max(5000),adjustments:z.record(z.object({allowance:money,deduction:money,note:z.string().max(1000)})),checks:z.array(z.string().max(40)).max(30)}).superRefine((s,ctx)=>{const ids=new Set(s.employees.map(e=>e.id));for(const key of ['employees','shifts','attendance','reservations','purchases'] as const){if(new Set(s[key].map(e=>e.id)).size!==s[key].length)ctx.addIssue({code:'custom',message:'중복된 항목입니다.'});}for(const item of [...s.shifts,...s.attendance])if(!ids.has(item.employeeId))ctx.addIssue({code:'custom',message:'직원 정보를 확인해 주세요.'});const open=s.attendance.filter(a=>!a.end);if(new Set(open.map(a=>a.employeeId)).size!==open.length)ctx.addIssue({code:'custom',message:'이미 출근 처리된 직원입니다.'});});
export type State=z.infer<typeof stateSchema>;
export type Employee=z.infer<typeof employeeSchema>;
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
export function datePlus(d:string,n:number){const x=new Date(d+'T12:00:00+09:00');x.setUTCDate(x.getUTCDate()+n);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(x)}
export function duration(start:string,end:string,rest=0){let a=Number(start.slice(0,2))*60+Number(start.slice(3)),b=Number(end.slice(0,2))*60+Number(end.slice(3));if(b<=a)b+=1440;return Math.max(0,b-a-rest)/60}
export function hours(a:State['attendance'][number]){return a.end?Math.max(0,(+new Date(a.end)-+new Date(a.start))/3600000-a.breakMinutes/60):0}
export function payroll(s:State,month:string){return s.employees.map(e=>{const records=s.attendance.filter(a=>a.employeeId===e.id&&a.end&&new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date(a.start)).slice(0,7)===month);const h=records.reduce((n,a)=>n+hours(a),0);const base=Math.round(h*e.wage);const adj=s.adjustments[month+':'+e.id]||{allowance:0,deduction:0,note:''};return {employee:e,hours:h,base,...adj,total:base+adj.allowance-adj.deduction}})}
export function seed():State{const d=today(),month=d.slice(0,7);const employees:Employee[]=['김민지','박준호','이서연','최현우','정다은','윤지호'].map((name,i)=>({id:'e'+i,name,role:i%2?'주방':'홀',type:i%2?'정직원':'파트타임',wage:[12000,14000,12000,13000,12500,13000][i],phone:'',joined:month+'-01',income:'미검토',insurance:'확인 필요',contract:i===1?'검토 중':'작성 전',contractText:''}));
const attendance:State['attendance']=[];for(let day=1;day<=Math.min(12,Number(d.slice(8))-1);day++)for(const e of employees)attendance.push({id:'a'+day+e.id,employeeId:e.id,start:month+'-'+String(day).padStart(2,'0')+'T01:00:00.000Z',end:month+'-'+String(day).padStart(2,'0')+'T08:00:00.000Z',breakMinutes:30,breakStart:null});
return {store:{name:'온기 식당',branch:'성수점'},employees,attendance,shifts:Array.from({length:7},(_,i)=>employees.slice(0,4).map((e,j)=>({id:'s'+i+e.id,employeeId:e.id,date:datePlus(d,i),start:j<2?'10:00':'17:00',end:j<2?'18:00':'22:00',breakMinutes:30}))).flat(),reservations:['김수빈','이정민','박성호','최유진','한지우'].map((name,i)=>({id:'r'+i,name,date:d,time:['12:00','12:30','18:00','18:30','19:00'][i],people:[2,4,2,6,4][i],table:['1번','2번','3번','단체석','4번'][i] as any,phone:'',note:i===3?'단체 예약 · 창가 자리 요청':'',status:'예약 확정'})),purchases:[['국내산 돼지고기','성수 정육',20,'kg',18000],['제철 채소','새벽 청과',8,'박스',32000],['쌀 20kg','풍년 식자재',6,'개',62000],['주류·음료','우리 주류',12,'박스',48000]].map(([name,vendor,quantity,unit,price],i)=>({id:'p'+i,name:String(name),vendor:String(vendor),quantity:Number(quantity),unit:unit as any,price:Number(price),date:d,category:i===3?'음료':'식재료'})),adjustments:{},checks:[]};}
