// 지시서 098: 2단계 인증(TOTP) — RFC 6238 값, 켜기·로그인 차단·코드 확인·비상 코드·끄기
import assert from 'node:assert/strict';
import {api} from '../dist/server/index.js';
import {authedTest,TEST_PASSWORD} from './test-auth.mjs';import {closeAll} from './test-db.mjs';
import {hotp,verifyTotp,base32,unbase32,sessionKeyOf} from '../lib/totp.ts';
let n=0;const ok=(l,v,e=true)=>{assert.deepEqual(v,e,l);console.log(`${++n}. PASS ${l}`)};
const rfc=new TextEncoder().encode('12345678901234567890');
ok('RFC 6238 T=59',await hotp(rfc,1,8),'94287082');ok('RFC 6238 T=1111111109',await hotp(rfc,37037036,8),'07081804');
ok('base32 round trip',[...unbase32(base32(rfc))].join(),[...rfc].join());
const sec=base32(rfc),now=59000;ok('verify current',await verifyTotp(sec,await hotp(rfc,1),now),1);ok('verify replay blocked',await verifyTotp(sec,await hotp(rfc,1),now,1),-1);ok('wrong code',await verifyTotp(sec,'000000',now),-1);
ok('jwt session id',sessionKeyOf('a.'+btoa(JSON.stringify({session_id:'S1'}))+'.c'),'sid:S1');
const T=await authedTest({origin:'https://qa.local'}),{headersFor,env,auth}=T;
const A=(body,token)=>api(new Request('https://qa.local/api/auth',{method:'POST',headers:{origin:'https://qa.local','content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify(body)}),env).then(async r=>({status:r.status,body:await r.json()}));
const acct=(token)=>api(new Request('https://qa.local/api/account',{headers:{authorization:'Bearer '+token}}),env).then(async r=>({status:r.status,body:await r.json()}));
const u=await auth.user('mfa');let tok=u.token;
ok('status off',(await A({action:'totpStatus'},tok)).body.enabled,false);
const s=await A({action:'totpSetup'},tok);ok('setup gives secret + uri',[s.status,s.body.uri.startsWith('otpauth://totp/')],[200,true]);
const code=async()=>hotp(unbase32(s.body.secret),Math.floor(Date.now()/30000));
ok('enable needs right code',(await A({action:'totpEnable',otp:'000000'},tok)).status,400);
let e=await A({action:'totpEnable',otp:await code()},tok);ok('enabled with 10 backup codes',[e.status,e.body.backupCodes.length],[200,10]);const backups=e.body.backupCodes;
ok('this session still works',(await acct(tok)).status,200);
let L=await A({action:'login',email:u.email,password:TEST_PASSWORD});ok('login asks for code',[L.status,L.body.mfaRequired,!!L.body.session?.access_token],[200,true,true]);
const t2=L.body.session.access_token;let a=await acct(t2);ok('password-only session blocked',[a.status,a.body.code],[401,'MFA_REQUIRED']);
ok('store blocked too',(await api(new Request('https://qa.local/api/store',{headers:{authorization:'Bearer '+t2}}),env)).status,401);
ok('wrong code refused',(await A({action:'totpVerify',otp:'123456'},t2)).status,400);
ok('backup code works once',(await A({action:'totpVerify',otp:backups[0]},t2)).status,200);ok('session now allowed',(await acct(t2)).status,200);
L=await A({action:'login',email:u.email,password:TEST_PASSWORD});const t3=L.body.session.access_token;
ok('used backup code refused',(await A({action:'totpVerify',otp:backups[0]},t3)).status,400);
ok('status shows 9 left',(await A({action:'totpStatus'},t2)).body.backupLeft,9);
ok('disable from unverified session refused',(await A({action:'totpDisable',otp:backups[1]},t3)).status,400);
ok('disable from verified session',(await A({action:'totpDisable',otp:backups[1]},t2)).body.enabled,false);
ok('after disable password login works',(await acct(t3)).status,200);
// 출시 준비: 광고성 정보 수신 동의(선택)
{const r=await A({action:'register',email:'mk@example.invalid',password:TEST_PASSWORD,name:'마케팅',role:'owner',agree:true,marketing:true});ok('register with marketing',r.status,200);
 const tk=r.body.session.access_token;let m=await A({action:'marketing'},tk);ok('marketing on at signup',m.body.on,true);
 m=await A({action:'marketing',on:false},tk);ok('turn off shows time',[m.body.on,!!m.body.changedAt],[false,true]);
 const r2=await A({action:'register',email:'mk2@example.invalid',password:TEST_PASSWORD,name:'안받음',role:'owner',agree:true});ok('default off',(await A({action:'marketing'},r2.body.session.access_token)).body.on,false);
 ok('under-14/consent required',(await A({action:'register',email:'mk3@example.invalid',password:TEST_PASSWORD,name:'x',role:'owner'})).status,400);}
console.log('PASS: 2단계 인증.');
await closeAll();
