import assert from 'node:assert/strict';
import {build} from 'rolldown';
const path='.superpowers/sdd/2026-10-11-hr-nine-features/hr-demo-test.mjs';
await build({input:'app/hr/demo-client.ts',platform:'node',output:{file:path,format:'esm'}});
const {createHrDemo,createHrDemoClient}=await import('../'+path);
let network=0;globalThis.fetch=async()=>{network++;throw Error('Demo must stay local')};
const s=createHrDemo(),owner=createHrDemoClient(s,'owner'),staff=createHrDemoClient(s,'employee'),manager=createHrDemoClient(s,'manager');
let n=0;const eq=(a,b,label)=>{assert.deepEqual(a,b,label);console.log('PASS '+(++n)+' '+label)},write=(c,scope,action,body={})=>c.post('/api/hr/'+scope,{action,requestId:crypto.randomUUID(),branchId:'branch-main',...body}),deny=async(p,status,label)=>{await assert.rejects(p,e=>e.status===status,label);console.log('PASS '+(++n)+' '+label)};
const emp=s.store.employees[0].id,buddy=s.store.employees[1].id;
const candidate=(await write(owner,'hiring','save',{name:'예시 지원자',phone:'',role:'홀',availability:'수·금',source:'소개',questions:''})).record;
let c=(await write(owner,'hiring','stage',{id:candidate.id,version:1,stage:'채용 결정',interviewAt:null})).record;
c=(await write(owner,'hiring','convert',{id:c.id,version:c.version,mode:'new',storeVersion:1,confirmed:true})).record;
eq(s.store.employees.find(e=>e.id===c.convertedEmployeeId).status,'입사 준비','hiring creates explicit unconfirmed onboarding');
await deny(staff.get('/api/hr/hiring'),403,'staff cannot view applicants');
let a=(await write(owner,'training','assignBuddy',{employeeId:emp,buddyId:buddy,from:'2020-01-01',until:'2099-12-31',steps:[{title:'오픈 순서',manualId:null}]})).record;
a=(await write(manager,'training','updateStep',{id:a.id,version:a.version,stepId:a.steps[0].id,progress:'awaiting_ack',note:'함께 확인'})).record;
await write(staff,'training','ackStep',{id:a.id,version:a.version,stepId:a.steps[0].id});eq(s.buddies.at(-1).steps[0].progress,'done','learner acknowledges buddy step');
const skill=(await write(owner,'training','saveSkill',{name:'음료 준비',manualId:null})).record;
const rec=(await write(owner,'training','setLevel',{employeeId:emp,skillId:skill.id,level:'도움받으면 가능',note:'다음 주 확인'})).record;
await deny(write(staff,'training','setLevel',{employeeId:emp,skillId:skill.id,level:'혼자 가능',note:''}),403,'no self certification');
await write(staff,'training','requestReview',{id:rec.id,version:rec.version});eq(!!s.skillRecords.at(-1).reviewRequestedAt,true,'skill review requested');
const existing=s.preferences.find(p=>p.employeeId===emp&&p.period==='month'&&p.periodKey===new Date().toISOString().slice(0,7));
const p=(await write(staff,'staffing','savePreference',{...(existing?{id:existing.id,version:existing.version}:{}),period:'month',periodKey:new Date().toISOString().slice(0,7),unit:'hours',min:20,max:40})).record;
await write(owner,'staffing','reviewPreference',{id:p.id,version:p.version,reviewNote:'편성 전 확인'});eq(!!s.preferences.at(-1).reviewedAt,true,'work preference reviewed');
eq((await owner.get('/api/hr/staffing')).rows.length>=2,true,'staffing derives actual schedule evidence');
let m=(await write(owner,'meetings','save',{employeeId:emp,assigneeId:'owner',topic:'첫 주 돌아보기',scheduledAt:new Date().toISOString(),sharedSummary:'다음 주 함께 연습해요',privateNote:'비공개 예시',status:'held'})).record.meeting;
eq((await staff.get('/api/hr/meetings')).meetings.some(x=>x.meeting.id===m.id),false,'unshared meeting hidden');
m=(await write(owner,'meetings','share',{id:m.id,version:m.version,confirmed:true})).record.meeting;
const mv=(await staff.get('/api/hr/meetings')).meetings.find(x=>x.meeting.id===m.id);eq('privateNote' in mv,false,'private note absent from staff DTO');
m=(await write(staff,'meetings','ack',{id:m.id,version:m.version})).record.meeting;eq(!!m.ackAt,true,'shared meeting acknowledged');
let cs=(await write(staff,'cases','submit',{subject:'교육 의견',body:'조금 더 연습하고 싶어요',assigneeId:null,visibilityConfirmed:true})).record.record;
await deny(manager.get('/api/hr/cases?id='+cs.id),404,'unassigned manager cannot read case');
await write(owner,'cases','reply',{id:cs.id,version:cs.version,body:'교육 시간을 잡아볼게요'});eq((await staff.get('/api/hr/cases?id='+cs.id)).messages.length,2,'case conversation shared only with participants');
let campaign=(await write(owner,'pulse','saveCampaign',{title:'첫 주 안내',questions:[{id:'q1',text:'안내가 도움이 되었나요?'}],employeeIds:[emp],opensAt:new Date(Date.now()-60000).toISOString(),closesAt:new Date(Date.now()+86400000).toISOString()})).record;
await write(owner,'pulse','publish',{id:campaign.id,version:campaign.version});await write(staff,'pulse','answer',{campaignId:campaign.id,values:{q1:4},comment:'좋아요',visibilityConfirmed:true});
eq((await owner.get('/api/hr/pulse')).campaigns.find(c=>c.campaign.id===campaign.id).summary.responded,1,'survey counts submitted answer');eq((await staff.get('/api/hr/pulse')).campaigns[0].summary,null,'staff cannot view named coworker answers');
let item=(await write(owner,'items','issue',{employeeId:emp,name:'예시 유니폼',quantity:2,dueAt:null,note:''})).record;
item=(await write(staff,'items','ack',{id:item.id,version:item.version})).record;
const request={action:'return',id:item.id,version:item.version,quantity:1,note:'',branchId:'branch-main',requestId:crypto.randomUUID()};await owner.post('/api/hr/items',request);await owner.post('/api/hr/items',request);eq(s.items.find(i=>i.id===item.id).returned,1,'duplicate return applies once');
await deny(write(owner,'items','return',{id:item.id,version:item.version,quantity:1,note:''}),409,'stale version conflicts without mutation');
const exp=await write(staff,'export','export',{mode:'self',selection:['meetings','items']});eq(JSON.stringify(exp).includes('비공개 예시'),false,'self export uses safe projections');
const fresh=createHrDemo();eq(fresh.candidates.some(c=>c.name==='예시 지원자'),false,'reset restores initial state');eq(network,0,'all demo actions use zero network requests');
console.log('PASS: HR demo '+n+' assertions');
