import assert from 'node:assert/strict';
import worker,{api} from '../dist/server/index.js';
import {authedTest} from './test-auth.mjs';import {closeAll} from './test-db.mjs';
const T=await authedTest({domain:'example.com'}),{q,headersFor}=T,env=T.env,DB=env.DB,userId=T.id;
let passed=0;function ok(label,actual,expected){assert.deepEqual(actual,expected,label);console.log(`${++passed}. PASS ${label}`)}
async function call(user,path,body,method){const r=await api(new Request('https://test.local'+path,{method:method||(body?'POST':'GET'),headers:{origin:'https://test.local',...(await headersFor(user))},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:r.status,data:await r.json()}}
const account=(u,b)=>call(u,'/api/account',b),join=(u,b)=>call(u,'/api/staff-join',b),store=(u,b,m)=>call(u,'/api/store',b,m);
for(const p of ['/app','/signup?plan=free','/employee?code=example','/staff-requests','/app/','/start','/try','/account']){const r=await worker.fetch(new Request('https://test.local'+p),{DB,ASSETS:{fetch:async r=>new Response(new URL(r.url).pathname,{status:new URL(r.url).pathname==='/'?200:404})}});ok('entry route '+p,r.status,200)}
ok('unknown route stays 404',(await worker.fetch(new Request('https://test.local/missing'),{DB,ASSETS:{fetch:async()=>new Response('',{status:404})}})).status,404);
ok('anonymous denied',(await join('')).status,401);
ok('free store creation',(await account('boss',{action:'onboard',storeName:'테스트',branchName:'본점',ownerName:'대표',plan:'free',acknowledged:true,dpaAgreed:true})).status,201);
let j=await join('boss');ok('owner role',j.data.owner,true);
ok('make shared code',(await join('boss',{action:'code',branchId:'branch-main',version:j.data.version})).status,200);
j=await join('boss');const code=j.data.codes[0].code;ok('one branch code',j.data.codes.length,1);
ok('invalid code',(await join('staff',{action:'apply',code:'wrong',name:'직원',phone:'01000000000'})).status,400);
ok('employee request',(await join('staff',{action:'apply',code,name:'직원',phone:'01000000000'})).status,200);
ok('duplicate request idempotent',(await join('staff',{action:'apply',code,name:'직원',phone:'01000000000'})).status,200);
ok('pending cannot see store',(await store('staff')).status,409);
let mine=await join('staff');ok('pending visible to self',mine.data.requests[0].status,'pending');ok('pending response hides wage',JSON.stringify(mine).includes('wage'),false);
ok('other employee sees no requests',(await join('stranger')).data.requests.length,0);
j=await join('boss');ok('owner receives one request',j.data.requests.length,1);const id=j.data.requests[0].id;
ok('employee cannot approve',(await join('staff',{action:'review',id,approve:true,payType:'시급',wage:10320,version:j.data.version})).status,403);
ok('stale approval blocked',(await join('boss',{action:'review',id,approve:true,payType:'시급',wage:10320,version:0})).status,409);
ok('approval without terms needs a wage',(await join('boss',{action:'review',id,approve:true,version:j.data.version})).data.code,'WAGE_REQUIRED');
ok('owner accepts',(await join('boss',{action:'review',id,approve:true,payType:'시급',wage:10320,version:j.data.version})).status,200);
ok('employee connected',(await join('staff')).data.connected,true);
let s=await store('staff');ok('employee access',s.data.access,'employee');ok('wage set by owner on approval',s.data.state.employees[0].wage,10320);
ok('employee cannot change account',(await account('staff',{action:'changePlan',plan:'team'})).status,403);
let boss=await store('boss'),eid=boss.data.state.employees[0].id;
ok('free contract confirmation blocked',(await store('boss',{action:'contract',id:eid,reason:'테스트',version:boss.data.version})).status,400);
ok('free contract queue blocked',(await store('boss',{action:'queueContract',id:eid,version:boss.data.version})).status,400);
ok('ordinary save preserves joins',(await store('boss',{state:boss.data.state,version:boss.data.version},'PUT')).status,200);
ok('join code survives save',(await join('boss')).data.codes[0].code,code);
ok('staff stays linked',(await store('staff')).status,200);
ok('second request',(await join('staff2',{action:'apply',code,name:'직원2',phone:'01000000000'})).status,200);
j=await join('boss');ok('reject request',(await join('boss',{action:'review',id:j.data.requests[0].id,approve:false,version:j.data.version})).status,200);
ok('rejected cannot access',(await store('staff2')).status,409);ok('rejected own status',(await join('staff2')).data.requests[0].status,'rejected');
ok('retry after rejection',(await join('staff2',{action:'apply',code,name:'직원2',phone:'01000000000'})).status,200);
ok('upgrade starter',(await account('boss',{action:'changePlan',plan:'starter'})).status,200);
boss=await store('boss');ok('paid contract queue allowed',(await store('boss',{action:'queueContract',id:eid,version:boss.data.version})).status,200);
ok('employee cannot use manager API',(await call('staff','/api/manager')).status,403);
boss=await store('boss');boss.data.state.employees[0].access='중간관리자';boss.data.state.employees[0].managerPermissions=['schedule','notices'];
ok('owner delegates manager duties',(await store('boss',{state:boss.data.state,version:boss.data.version},'PUT')).status,200);
let manager=await call('staff','/api/manager');ok('manager permission selection',manager.data.permissions,['schedule','notices']);
ok('manager payload hides wage',JSON.stringify(manager.data).includes('wage'),false);
ok('manager cannot grant own roles',(await store('staff',{state:(await store('staff')).data.state,version:manager.data.version},'PUT')).status,403);
ok('manager cannot manage foreign employee',(await call('staff','/api/manager',{action:'saveShift',version:manager.data.version,shift:{employeeId:'foreign',date:'2026-10-10',start:'09:00',end:'18:00',breakMinutes:60}})).status,403);
ok('delegated manager adds shift',(await call('staff','/api/manager',{action:'saveShift',version:manager.data.version,shift:{employeeId:eid,date:'2026-10-10',start:'09:00',end:'18:00',breakMinutes:60}})).status,200);
manager=await call('staff','/api/manager');ok('unassigned approval blocked',(await call('staff','/api/manager',{action:'reviewLeave',version:manager.data.version,id:'x',approve:true,payType:'시급',wage:10320,comment:'test'})).status,403);
ok('manager can post branch notice',(await call('staff','/api/manager',{action:'postNotice',version:manager.data.version,title:'테스트 공지',body:'가상 검수'})).status,200);
boss=await store('boss');boss.data.state.employees[0].managerPermissions=[];await store('boss',{state:boss.data.state,version:boss.data.version},'PUT');manager=await call('staff','/api/manager');
ok('revoked permission blocked immediately',(await call('staff','/api/manager',{action:'postNotice',version:manager.data.version,title:'test',body:'test'})).status,403);
console.log(`Entry/join/contracts/manager checks: ${passed} passed`);
await closeAll();
