import test from 'node:test';
import assert from 'node:assert/strict';
import {applyDemoSwap} from '../lib/demo-swaps.ts';
const fixture=()=>({team:{employees:[{id:'a',name:'가',branchId:'b'},{id:'z',name:'나',branchId:'b'}],shifts:[{id:'s',employeeId:'a',date:'2026-10-12',start:'09:00',end:'15:00'},{id:'c',employeeId:'z',date:'2026-10-13',start:'09:00',end:'15:00'}],payrollRuns:{}},ops:{swaps:[],leaves:[]}});
const run=(state,b,selfId='a')=>applyDemoSwap(state.team,state.ops,b,{selfId,today:'2026-10-10',now:'2026-10-10T10:00:00Z'});
test('대타는 수락까지 원본 유지, 사장님 승인 뒤 근무자 변경',()=>{let s=fixture();s=run(s,{action:'requestSwap',shiftId:'s',kind:'대타',reason:'시험'});const id=s.ops.swaps[0].id;s=run(s,{action:'acceptSwap',id},'z');assert.equal(s.team.shifts[0].employeeId,'a');assert.throws(()=>run(s,{action:'reviewSwap',id,approve:true},'z'),/사장님/);s=run(s,{action:'reviewSwap',id,approve:true},null);assert.equal(s.team.shifts[0].employeeId,'z');assert.equal(s.ops.swaps[0].status,'승인');});
test('교대 승인 시 두 근무가 함께 변경',()=>{let s=fixture();s=run(s,{action:'requestSwap',shiftId:'s',kind:'교대',reason:'일정'});const id=s.ops.swaps[0].id;s=run(s,{action:'acceptSwap',id,myShiftId:'c'},'z');s=run(s,{action:'reviewSwap',id,approve:true},null);assert.deepEqual(s.team.shifts.map(x=>x.employeeId),['z','a']);});
test('본인 아닌 요청, 중복 요청, 겹치는 근무 수락 차단',()=>{let s=fixture();assert.throws(()=>run(s,{action:'requestSwap',shiftId:'s',kind:'대타',reason:'시험'},'z'),/본인/);s=run(s,{action:'requestSwap',shiftId:'s',kind:'대타',reason:'시험'});assert.throws(()=>run(s,{action:'requestSwap',shiftId:'s',kind:'대타',reason:'또'}),/이미/);s.team.shifts.push({id:'overlap',employeeId:'z',date:'2026-10-12',start:'14:00',end:'18:00'});assert.throws(()=>run(s,{action:'acceptSwap',id:s.ops.swaps[0].id},'z'),/겹치/);});
test('수락 뒤 변경된 근무와 확정 급여·휴가 차단',()=>{let s=fixture();s=run(s,{action:'requestSwap',shiftId:'s',kind:'대타',reason:'시험'});let id=s.ops.swaps[0].id;s=run(s,{action:'acceptSwap',id},'z');s.team.shifts[0].start='10:00';assert.throws(()=>run(s,{action:'reviewSwap',id,approve:true},null),/바뀌/);s=fixture();s=run(s,{action:'requestSwap',shiftId:'s',kind:'대타',reason:'시험'});id=s.ops.swaps[0].id;s.ops.leaves.push({employeeId:'z',status:'승인',start:'2026-10-12',end:'2026-10-12'});assert.throws(()=>run(s,{action:'acceptSwap',id},'z'),/휴가/);s.ops.leaves=[];s.team.payrollRuns.x={locked:true,month:'2026-10',rows:[{employeeId:'z'}]};assert.throws(()=>run(s,{action:'acceptSwap',id},'z'),/확정/);});
