import {useState} from 'react';
import {CANDIDATE_STAGES,type Candidate,type CandidateStage,type HiringView,type HrPanelProps,type HrMutationResult} from '../../lib/hr/types';
import {useHrData,useHrAction,Field,Empty} from './components';
const blank=()=>({name:'',phone:'',role:'홀',availability:'',source:'',questions:''});
export function HiringPanel({client,branchId}:HrPanelProps){
 const {data,error,loading,reload}=useHrData<HiringView>(client,'/api/hr/hiring?branch='+encodeURIComponent(branchId));
 const [draft,setDraft]=useState(blank),[selected,setSelected]=useState<Candidate|null>(null),[filter,setFilter]=useState('전체');
 const [stage,setStage]=useState<CandidateStage>('지원 접수'),[interview,setInterview]=useState(''),[mode,setMode]=useState<'new'|'link'>('new'),[employeeId,setEmployee]=useState(''),[confirmed,setConfirmed]=useState(false),[days,setDays]=useState('');
 const action=useHrAction(client,branchId,reload),choose=(c:Candidate|null)=>{setSelected(c);setDraft(c?{name:c.name,phone:c.phone,role:c.role,availability:c.availability,source:c.source,questions:c.questions}:blank());setStage(c?.stage||'지원 접수');setInterview(c?.interviewAt?new Date(Date.parse(c.interviewAt)+9*3600000).toISOString().slice(0,16):'');setConfirmed(false)};
 const save=async(body:object)=>{const r=await action.run<HrMutationResult<Candidate>>('/api/hr/hiring',body);if(r)choose(r.record)};
 if(!data)return <section className="hr-panel"><h2>채용 지원자</h2>{error?<p role="alert">{error}<button onClick={reload}>다시 연결</button></p>:<p role="status">지원자 목록을 확인하고 있어요.</p>}</section>;
 return <><section className="hr-panel"><h2>좋은 동료를 만나는 과정, 한곳에.</h2><p>지원 내용을 직접 기록하고 면접과 채용 결정을 이어가요. 직원 등록은 사장님이 마지막으로 확인해요.</p>
 <div className="hr-grid"><div><Field label="지원 상태로 보기"><select value={filter} onChange={e=>setFilter(e.target.value)}>{['전체',...CANDIDATE_STAGES].map(s=><option key={s}>{s}</option>)}</select></Field>
 {!data.candidates.length?<Empty>아직 지원자가 없어요. 이름과 가능한 근무 시간을 먼저 적어 보세요.</Empty>:<ul className="hr-records">{data.candidates.filter(c=>filter==='전체'||c.stage===filter).map(c=><li key={c.id}><div><strong>{c.name}</strong><p>{c.role} · {c.stage}</p><small>{c.interviewAt?new Date(c.interviewAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'면접 일정 미정'}</small>{c.convertedEmployeeId&&<p className="hr-tag">직원 연결 완료</p>}</div><button onClick={()=>choose(c)}>지원 내용 보기</button></li>)}</ul>}</div>
 <div><div className="hr-actions"><h3>{selected?selected.name+' 지원 내용':'새 지원자 기록'}</h3>{selected&&<button onClick={()=>choose(null)}>새 지원자</button>}</div><form className="hr-form" onSubmit={e=>{e.preventDefault();void save({action:'save',...draft,...(selected?{id:selected.id,version:selected.version}:{})})}}>
 <Field label="지원자 이름"><input required maxLength={40} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="연락처"><input type="tel" maxLength={30} value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></Field><Field label="희망 업무"><input required maxLength={20} value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}/></Field><Field label="가능한 근무 시간"><textarea maxLength={1000} value={draft.availability} onChange={e=>setDraft({...draft,availability:e.target.value})}/></Field><Field label="지원 경로"><input maxLength={80} value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})}/></Field><Field label="면접에서 확인할 내용"><textarea maxLength={2000} value={draft.questions} onChange={e=>setDraft({...draft,questions:e.target.value})}/></Field><button className="hr-primary" disabled={action.busy}>지원 내용 저장</button></form></div></div>{action.feedback}
 {selected&&<div className="hr-grid hr-separator"><form className="hr-form" onSubmit={e=>{e.preventDefault();void save({action:'stage',id:selected.id,version:selected.version,stage,interviewAt:interview?new Date(interview+'+09:00').toISOString():null})}}><h3>면접·진행 상태</h3><Field label="변경할 지원 상태"><select value={stage} onChange={e=>setStage(e.target.value as CandidateStage)}>{CANDIDATE_STAGES.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="면접 일시" hint="한국 시간 기준이에요."><input type="datetime-local" value={interview} onChange={e=>setInterview(e.target.value)} required={stage==='면접 예정'}/></Field><button disabled={action.busy}>상태 저장</button></form>
 {data.owner&&selected.stage==='채용 결정'&&!selected.convertedEmployeeId&&<form className="hr-form" onSubmit={e=>{e.preventDefault();void save({action:'convert',id:selected.id,version:selected.version,mode,employeeId:mode==='link'?employeeId:undefined,confirmed,storeVersion:data.storeVersion})}}><h3>사장님 최종 확인</h3><p>입사 준비로 연결한 뒤 임금과 계약을 확인해요. 연락처가 같아도 자동으로 연결하지 않아요.</p><Field label="직원 연결 방법"><select value={mode} onChange={e=>setMode(e.target.value as 'new'|'link')}><option value="new">새 직원으로 입사 준비</option><option value="link">기존 직원과 연결</option></select></Field>{mode==='link'&&<Field label="연결할 기존 직원"><select required value={employeeId} onChange={e=>setEmployee(e.target.value)}><option value="">선택해 주세요</option>{data.employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></Field>}<label className="hr-check"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>채용 결정과 연결할 직원을 확인했어요.</label><button className="hr-primary" disabled={action.busy||!confirmed}>직원과 연결</button></form>}
 {selected.convertedEmployeeId&&<div className="hr-hint"><h3>입사 준비를 이어가세요.</h3><p>직원 관리에서 임금·소득 구분·계약을 확인해 주세요.</p><a href={'/app?tab=team&employee='+encodeURIComponent(selected.convertedEmployeeId)}>직원 관리 열기 →</a></div>}</div>}
 </section>{data.owner&&<section className="hr-panel"><h2>종료 지원자 보관 설정</h2><p>현재 {data.candidateRetentionDays?data.candidateRetentionDays+'일 보관':'자동 파기 기한 미설정'}이에요. 보관 일수를 정하면 종료·철회한 지원자만 해당 날짜 이후 정리해요.</p><form className="hr-form hr-form-inline" onSubmit={e=>{e.preventDefault();void action.run('/api/hr/hiring',{action:'retentionSettings',candidateRetentionDays:days?Number(days):null})}}><Field label="보관 일수" hint="비워 두고 저장하면 자동 파기를 사용하지 않아요."><input type="number" min={1} max={3650} value={days} onChange={e=>setDays(e.target.value)} placeholder={data.candidateRetentionDays?.toString()||'미설정'}/></Field><button disabled={action.busy}>보관 설정 저장</button></form><p>파기 예정 {data.deletionPreview.length}건</p><ul>{data.deletionPreview.map(c=><li key={c.id}>{c.name} · {new Date(c.purgeAt).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})} 이후</li>)}</ul></section>}{loading&&<p role="status">최신 내용을 확인하고 있어요.</p>}</>;
}
