import type {HrContext,HrDatabase,ItemAssignment,ItemEvent,ItemsView} from '../../lib/hr/types';import {itemsSchema} from '../../lib/hr/items';import {staffGone} from '../../lib/staff-access';import {person,isManager} from './people';import {deny,notFound,conflict,contextView} from './context';import {listRecords,getRecord,makeRecord,revise,putRecord,expectVersion} from './records';import {withHrMutation,fingerprint} from './mutation';
export async function itemsRead(db:HrDatabase,c:HrContext,url:URL):Promise<ItemsView>{const manage=isManager(c,'items'),employee=url.searchParams.get('employee');if(employee&&!manage&&employee!==c.selfId)deny();const items=(await listRecords<ItemAssignment>(db,c,'hr_item_assignments')).filter(r=>(manage||r.employeeId===c.selfId)&&(!employee||r.employeeId===employee)),ids=new Set(items.map(i=>i.id));return{context:contextView(c),manage,items,events:(await listRecords<ItemEvent>(db,c,'hr_item_events')).filter(e=>ids.has(e.assignmentId)),people:c.store.employees.filter(e=>e.branchId===c.branchId&&(manage||e.id===c.selfId)).map(e=>({id:e.id,name:e.name,departed:staffGone(e)}))}}
export async function itemsWrite(db:HrDatabase,ctx:HrContext,input:unknown){const b=itemsSchema.parse(input),auth=(c:HrContext)=>{if(b.action!=='ack'&&!isManager(c,'items'))deny();if(b.action==='ack'&&!c.selfId)deny()};auth(ctx);const read=async(tx:HrDatabase,c:HrContext,id:string)=>{const r=await getRecord<ItemAssignment>(tx,c,'hr_item_assignments',id);if(!isManager(c,'items')&&r.employeeId!==c.selfId)deny();return r};
 return withHrMutation<ItemAssignment>(db,ctx,{...b,operation:'items:'+b.action,fingerprint:await fingerprint(b),authorize:auth,target:r=>r.id,replay:read},async(tx,c)=>{
  let r:ItemAssignment,quantity=0;
  if(b.action==='issue'){person(c,b.employeeId);quantity=b.quantity;r=await putRecord(tx,c,'hr_item_assignments',makeRecord(c,{employeeId:b.employeeId,name:b.name,issued:b.quantity,returned:0,lost:0,issuedAt:c.now,dueAt:b.dueAt,receivedAt:null,note:b.note}))}
  else{const old=await getRecord<ItemAssignment>(tx,c,'hr_item_assignments',b.id);if(b.action==='ack'&&old.employeeId!==c.selfId)deny();expectVersion(old,b.version);let patch:Partial<ItemAssignment>={};if(b.action==='ack'){if(old.receivedAt)conflict();patch={receivedAt:c.now}}if(b.action==='requestReturn')patch={dueAt:b.dueAt};if(b.action==='return'||b.action==='lost'){quantity=b.quantity;if(quantity>old.issued-old.returned-old.lost)conflict();patch=b.action==='return'?{returned:old.returned+quantity}:{lost:old.lost+quantity}}r=await putRecord(tx,c,'hr_item_assignments',revise(c,old,patch),old)}
  await putRecord(tx,c,'hr_item_events',makeRecord(c,{assignmentId:r.id,kind:b.action,quantity,note:'note'in b?b.note:''}));return r;
 });
}
