import {useState} from 'react';
import type {HrPanelProps,MeetingsView,MeetingView,MeetingAction} from '../../lib/hr/types';
import {ChangeHistory,Field,Empty,useHrData,useHrAction} from './components';
const meetingStatus={scheduled:'예정',held:'진행함',closed:'마무리'};
export function MeetingsPanel(props:HrPanelProps){const {client,branchId}=props,{data,error,reload}=useHrData<MeetingsView>(client,'/api/hr/meetings?branch='+encodeURIComponent(branchId)),action=useHrAction(client,branchId,reload);
 if(!data)return <section className="hr-panel"><h2>면담·약속</h2><p role={error?'alert':'status'}>{error||'면담 기록을 확인하고 있어요.'}</p><button onClick={reload}>다시 연결</button></section>;
 return <section className="hr-panel"><h2>나눈 이야기가, 다음 약속으로 이어지도록.</h2><p>공유 요약은 해당 직원과 사장님·공동관리자·지정 면담 담당자만 확인해요. 담당 메모는 직원에게 보이지 않아요.</p>{action.feedback}{data.manage&&<details><summary>새 면담 준비하기</summary><MeetingEditor data={data} busy={action.busy} save={b=>action.run('/api/hr/meetings',b)}/></details>}{!data.meetings.length?<Empty>아직 공유된 면담이 없어요. 대화와 약속을 기록하면 여기서 이어갈 수 있어요.</Empty>:data.meetings.map(v=><MeetingRecord key={v.meeting.id} {...props} data={data} v={v} busy={action.busy} save={b=>action.run('/api/hr/meetings',b)}/>)}</section>;
}
function MeetingEditor({data,v,busy,save}:{data:MeetingsView;v?:MeetingView;busy:boolean;save:(b:object)=>unknown}){const m=v?.meeting,[employee,setEmployee]=useState(m?.employeeId||''),[assignee,setAssignee]=useState(m?.assigneeId||(data.context.selfId||'owner')),[at,setAt]=useState(m?new Date(Date.parse(m.scheduledAt)+9*3600000).toISOString().slice(0,16):''),[topic,setTopic]=useState(m?.topic||''),[summary,setSummary]=useState(m?.sharedSummary||''),[note,setNote]=useState(v?.privateNote||''),[status,setStatus]=useState(m?.status||'scheduled');return <form className="hr-form hr-separator" onSubmit={e=>{e.preventDefault();save({action:'save',...(m?{id:m.id,version:m.version}:{}),employeeId:employee,assigneeId:assignee,scheduledAt:new Date(at+'+09:00').toISOString(),topic,sharedSummary:summary,privateNote:note,status})}}><div className="hr-grid"><Field label="면담 직원"><select required disabled={!!m} value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">선택해 주세요</option>{data.context.employees.filter(e=>e.id!==data.context.selfId).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="면담 담당자"><select value={assignee} onChange={e=>setAssignee(e.target.value)}>{data.assignees.filter(e=>data.context.access==='owner'||e.id===data.context.selfId).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="면담 일시 · 한국 시간"><input required type="datetime-local" value={at} onChange={e=>setAt(e.target.value)}/></Field><Field label="면담 상태"><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}>{Object.entries(meetingStatus).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field></div><Field label="면담 주제"><input required maxLength={100} value={topic} onChange={e=>setTopic(e.target.value)}/></Field><Field label="직원에게 공유할 요약"><textarea maxLength={2000} value={summary} onChange={e=>setSummary(e.target.value)}/></Field><Field label="담당자 비공개 메모" hint="사장님·공동관리자와 현재 지정된 면담 담당자만 볼 수 있어요."><textarea maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></Field><p className="hr-hint">저장 후 ‘공유 미리보기’를 확인하고 직접 공유해 주세요. 공유한 요약을 수정하면 다시 공유하기 전까지 직원 화면에서 숨겨요.</p><button disabled={busy} className="hr-primary">면담 내용 저장</button></form>}
function MeetingRecord({data,v,busy,save,selfId}:HrPanelProps&{data:MeetingsView;v:MeetingsView['meetings'][number];busy:boolean;save:(b:object)=>unknown}){const m=v.meeting,[confirm,setConfirm]=useState(false),[comment,setComment]=useState(''),[assignee,setAssignee]=useState('');return <article className="hr-separator"><span className="hr-tag">{meetingStatus[m.status]} · {m.sharedAt?'직원과 공유함':'공유 전'}</span><h3>{m.topic} · {data.context.employees.find(e=>e.id===m.employeeId)?.name||'이전 소속 직원'}</h3><p>{new Date(m.scheduledAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>{v.handover&&<p className="hr-hint">이전 담당자의 권한이 끝났어요. 사장님이 새 담당자에게 인계해 주세요.</p>}{v.editable&&<details><summary>면담 기록 수정</summary><MeetingEditor data={data} v={v} busy={busy} save={save}/></details>}
 <div className="hr-hint"><h3>직원 화면에 보이는 공유 요약</h3><p className="hr-preline">{m.sharedSummary||'아직 작성하지 않았어요.'}</p><ul>{v.actions.map(a=><li key={a.id}>{a.text} · {a.due}까지</li>)}</ul></div>{v.editable&&<details><summary>담당자 비공개 메모 보기</summary><p className="hr-preline">{v.privateNote||'아직 메모가 없어요.'}</p></details>}
 {v.editable&&!m.sharedAt&&<form className="hr-form hr-separator" onSubmit={e=>{e.preventDefault();save({action:'share',id:m.id,version:m.version,confirmed:confirm})}}><label className="hr-check"><input required type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>요약과 약속을 해당 직원에게 공유하는 것을 확인했어요.</label><button disabled={busy||!confirm}>직원에게 공유</button></form>}{m.employeeId===selfId&&m.sharedAt&&<button disabled={busy||!!m.ackAt} onClick={()=>save({action:'ack',id:m.id,version:m.version})}>{m.ackAt?'공유 내용 확인함':'공유 내용 확인했어요'}</button>}
 <ChangeHistory record={m} people={data.context.employees}/><h3>함께 정한 약속</h3>{v.editable&&<details><summary>약속 추가</summary><ActionEditor data={data} meetingId={m.id} version={m.version} busy={busy} save={save}/></details>}{v.actions.map(a=><div className="hr-hint" key={a.id}><strong>{a.text}</strong><p>{a.due}까지 · {a.status==='done'?'완료':'진행 중'}</p><details><summary>기한 변경 기록</summary><ul>{a.history.map((h,i)=><li key={i}>{h.due} · {new Date(h.at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})} 기록</li>)}</ul></details>{v.editable&&<details><summary>약속 수정</summary><ActionEditor data={data} meetingId={m.id} version={m.version} a={a} busy={busy} save={save}/></details>}{a.status==='open'&&(v.editable||a.employeeId===selfId)&&<button disabled={busy} onClick={()=>save({action:'actionComplete',meetingId:m.id,version:m.version,id:a.id,actionVersion:a.version})}>약속 완료 기록</button>}</div>)}
 {m.sharedAt&&<><h3>공유 대화</h3><ul className="hr-records">{v.comments.map(c=><li key={c.id}><div><small>{new Date(c.createdAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</small><p className="hr-preline">{c.body}</p></div></li>)}</ul><form className="hr-form" onSubmit={e=>{e.preventDefault();save({action:'comment',id:m.id,version:m.version,body:comment})}}><Field label="공유 대화에 남길 의견"><textarea required maxLength={1000} value={comment} onChange={e=>setComment(e.target.value)}/></Field><button disabled={busy}>의견 남기기</button></form></>}
 {data.context.access==='owner'&&<details><summary>면담 담당자 인계</summary><form className="hr-actions" onSubmit={e=>{e.preventDefault();save({action:'reassign',id:m.id,version:m.version,assigneeId:assignee})}}><Field label="인계할 담당자"><select required value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">선택해 주세요</option>{data.assignees.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><button disabled={busy}>담당자에게 인계</button></form></details>}</article>}
function ActionEditor({data,meetingId,version,a,busy,save}:{data:MeetingsView;meetingId:string;version:number;a?:MeetingAction;busy:boolean;save:(b:object)=>unknown}){const [text,setText]=useState(a?.text||''),[employee,setEmployee]=useState(a?.employeeId||''),[due,setDue]=useState(a?.due||'');return <form className="hr-form" onSubmit={e=>{e.preventDefault();save({action:'action',meetingId,version,...(a?{id:a.id,actionVersion:a.version}:{}),text,employeeId:employee,due})}}><Field label="함께 정한 약속"><input required maxLength={200} value={text} onChange={e=>setText(e.target.value)}/></Field><Field label="약속을 수행할 직원"><select required value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">선택해 주세요</option>{data.context.employees.filter(e=>{const m=data.meetings.find(v=>v.meeting.id===meetingId)?.meeting;return e.id===m?.employeeId||e.id===m?.assigneeId}).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="약속 기한"><input required type="date" value={due} onChange={e=>setDue(e.target.value)}/></Field><button disabled={busy}>약속 저장</button></form>}
