import type {HrContext,HrDatabase,HrMeta,PulseCampaign,PulseAnswer,PulseView} from '../../lib/hr/types';import {pulseSchema,pulseSummary} from '../../lib/hr/pulse';import {isManager,person} from './people';import {deny,notFound,HrError,contextView} from './context';import {listRecords,getRecord,putRecord,makeRecord,revise,expectVersion} from './records';import {withHrMutation,fingerprint} from './mutation';
export async function pulseRead(db:HrDatabase,c:HrContext,url:URL):Promise<PulseView|PulseAnswer>{const manage=isManager(c,'pulse'),answers=await listRecords<PulseAnswer>(db,c,'hr_pulse_answers'),answerId=url.searchParams.get('answerId');if(answerId){const a=answers.find(a=>a.id===answerId&&(manage||a.employeeId===c.selfId));if(!a)notFound();return a}return{context:contextView(c),manage,campaigns:(await listRecords<PulseCampaign>(db,c,'hr_pulse_campaigns')).filter(p=>manage||p.status!=='draft'&&p.employeeIds.includes(c.selfId!)).map(p=>({campaign:manage?p:{...p,employeeIds:[c.selfId!]},answers:answers.filter(a=>a.campaignId===p.id&&(manage||a.employeeId===c.selfId)),summary:manage?pulseSummary(p,answers):null}))}}
export async function pulseWrite(db:HrDatabase,ctx:HrContext,input:unknown){const b=pulseSchema.parse(input),auth=(c:HrContext)=>{if(b.action!=='answer'&&!isManager(c,'pulse'))deny();if(b.action==='answer'&&!c.selfId)deny()};auth(ctx);const table=b.action==='answer'?'hr_pulse_answers':'hr_pulse_campaigns';
 return withHrMutation<HrMeta>(db,ctx,{...b,operation:'pulse:'+b.action,fingerprint:await fingerprint(b),authorize:auth,target:r=>r.id,replay:async(tx,c,id)=>{const r=await getRecord<any>(tx,c,table,id);if(table==='hr_pulse_answers'&&r.employeeId!==c.selfId&&!isManager(c,'pulse'))notFound();return r}},async(tx,c)=>{
  if(b.action==='saveCampaign'){if(Date.parse(b.opensAt)>=Date.parse(b.closesAt)||new Set(b.questions.map(q=>q.id)).size!==b.questions.length||new Set(b.employeeIds).size!==b.employeeIds.length)throw new HrError(400,'기간·질문·대상 직원 중복을 확인해 주세요.');for(const id of b.employeeIds)person(c,id);let old:PulseCampaign|undefined;if(b.id){old=await getRecord<PulseCampaign>(tx,c,table,b.id);expectVersion(old,b.version);if(old.status!=='draft')throw new HrError(409,'공개한 설문은 변경할 수 없어요. 새 설문을 만들어 주세요.')}const patch={title:b.title,questions:b.questions,employeeIds:b.employeeIds,opensAt:b.opensAt,closesAt:b.closesAt,status:'draft' as const};return putRecord(tx,c,table,old?revise(c,old,patch):makeRecord(c,patch),old)}
  if(b.action==='answer'){const p=await getRecord<PulseCampaign>(tx,c,'hr_pulse_campaigns',b.campaignId);if(!p.employeeIds.includes(c.selfId!))deny();if(p.status!=='open'||Date.parse(c.now)<Date.parse(p.opensAt)||Date.parse(c.now)>=Date.parse(p.closesAt))throw new HrError(409,'응답 기간이 끝났거나 아직 시작 전이에요.');if(Object.keys(b.values).length!==p.questions.length||p.questions.some(q=>!Object.hasOwn(b.values,q.id)))throw new HrError(400,'모든 질문에 1~5점으로 답해 주세요.');const old=(await listRecords<PulseAnswer>(tx,c,table)).find(a=>a.campaignId===p.id&&a.employeeId===c.selfId);if(b.id&&old?.id!==b.id)notFound();if(old)expectVersion(old,b.version);const patch={campaignId:p.id,employeeId:c.selfId!,values:b.values,comment:b.comment,submittedAt:c.now};return putRecord(tx,c,table,old?revise(c,old,patch):makeRecord(c,patch),old)}
  const old=await getRecord<PulseCampaign>(tx,c,table,b.id);expectVersion(old,b.version);if(b.action==='publish'){if(old.status!=='draft'||Date.parse(old.closesAt)<=Date.parse(c.now))throw new HrError(409,'초안과 마감 시간을 확인해 주세요.');for(const id of old.employeeIds)person(c,id)}return putRecord(tx,c,table,revise(c,old,{status:b.action==='publish'?'open':'closed'}),old);
 });
}
