import {useState} from 'react';
import type {HrPanelProps,StaffingView,WorkPreference} from '../../lib/hr/types';
import {ChangeHistory,Field,Empty,useHrData,useHrAction} from './components';
export function StaffingPanel({client,branchId,selfId,demo}:HrPanelProps){
 const [period,setPeriod]=useState<'week'|'month'>('month'),[key,setKey]=useState(new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}).slice(0,7)),[unit,setUnit]=useState<'hours'|'days'>('hours'),[min,setMin]=useState(''),[max,setMax]=useState('');
 const {data,error,reload}=useHrData<StaffingView>(client,'/api/hr/staffing?branch='+encodeURIComponent(branchId)+'&period='+period+'&key='+encodeURIComponent(key));const action=useHrAction(client,branchId,reload);
 const mine=data?.preferences.find(p=>p.employeeId===selfId),name=(id:string)=>data?.context.employees.find(e=>e.id===id)?.name||'이전 소속 직원';
 return <section className="hr-panel"><h2>원하는 만큼, 고르게 일하고 있는지.</h2><p>희망 근무량과 실제 편성을 나란히 확인해요. 가능한 시간·계약 조건과는 별도이며, 근무표를 자동으로 바꾸지 않아요.</p><div className="hr-grid"><Field label="비교할 기간"><select value={period} onChange={e=>{setPeriod(e.target.value as 'week'|'month');setKey('')}}><option value="month">월간</option><option value="week">주간</option></select></Field><Field label={period==='month'?'대상 월':'주 시작일'} hint={period==='week'?'매장에 설정된 주 시작일(월요일 또는 일요일)을 선택해 주세요.':undefined}><input type={period==='month'?'month':'date'} value={key} onChange={e=>setKey(e.target.value)}/></Field></div>{error&&<p role="alert">{error}</p>}{action.feedback}{!data?<p role="status">기간을 선택하면 배정 내용을 볼 수 있어요.</p>:<>
 <p className="hr-hint">{data.from} ~ {data.to} · 근무 시작일 기준 · 휴게시간 제외</p>{selfId&&<form className="hr-form hr-separator" onSubmit={e=>{e.preventDefault();void action.run('/api/hr/staffing',{action:'savePreference',period,periodKey:key,unit,min:Number(min),max:Number(max),...(mine?{id:mine.id,version:mine.version}:{})})}}><h3>내 희망 근무량</h3>{mine&&<p>현재 희망: {mine.min}~{mine.max}{mine.unit==='hours'?'시간':'일'} · {mine.reviewedAt?'담당자 확인함':'아직 검토 전'}</p>}<div className="hr-grid"><Field label="희망 기준"><select value={unit} onChange={e=>setUnit(e.target.value as 'hours'|'days')}><option value="hours">시간</option><option value="days">근무일</option></select></Field><Field label="최소 희망량"><input required type="number" step={unit==='days'?1:0.5} min={0} value={min} onChange={e=>setMin(e.target.value)}/></Field><Field label="최대 희망량"><input required type="number" step={unit==='days'?1:0.5} min={0} value={max} onChange={e=>setMax(e.target.value)}/></Field></div><button className="hr-primary" disabled={action.busy}>내 희망 저장</button></form>}
 <div className="hr-staffing-cards">{data.rows.map(r=>{const p=data.preferences.find(p=>p.employeeId===r.employeeId);return <article className="hr-separator" key={r.employeeId}><h3>{name(r.employeeId)}</h3><div className="hr-stats"><div><strong>{r.plannedHours}시간</strong>편성 시간</div><div><strong>{r.shiftDays}일</strong>근무 시작일</div><div><strong>{r.weekendStarts}회</strong>주말 시작 근무</div><div><strong>{r.closingConfigured?r.closingShifts+'회':'미설정'}</strong>마감 근무</div><div><strong>{r.longestRun}일</strong>최장 연속 근무</div></div><p>희망 {p?p.min+'~'+p.max+(p.unit==='hours'?'시간':'일'):'미입력'} · 차이 {r.preferenceGap===null?'비교할 희망 없음':r.preferenceGap===0?'희망 범위 안':(r.preferenceGap>0?'+':'')+r.preferenceGap+(p?.unit==='days'?'일':'시간')}</p>{p&&<ChangeHistory record={p} people={data.context.employees}/>} {p?.reviewNote&&<p>검토 메모: {p.reviewNote}</p>}{data.manage&&p&&<PreferenceReview key={p.id} p={p} busy={action.busy} save={b=>action.run('/api/hr/staffing',b)}/>}<details><summary>계산에 사용한 근무 {r.evidenceShiftIds.length}건</summary><ul>{data.evidence.filter(s=>r.evidenceShiftIds.includes(s.id)).map(s=><li key={s.id}>{s.date} · {s.start}~{s.end} · 휴게 {s.breakMinutes}분{s.date<data.from||s.date>data.to?' · 연속일 확인 근거':''}</li>)}</ul></details></article>})}</div>{!data.rows.length&&<Empty>이 기간에 비교할 직원이 없어요.</Empty>}{data.selfAllBranchHours!==null&&<p className="hr-hint">내 전체 매장 편성: {data.selfAllBranchHours}시간</p>}{data.unconfirmedSkills.map(x=><p className="hr-hint" key={x.employeeId+x.skill}>{name(x.employeeId)} · ‘{x.skill}’ 숙련은 아직 확인 전이에요. 배정 전에 담당자와 확인해 주세요.</p>)}{data.manage&&<a href={(demo?'/demo?screen=schedule&branch=':'/app?screen=schedule&branch=')+encodeURIComponent(branchId)}>근무표에서 검토·공개하기 →</a>}</>}
 </section>;
}
function PreferenceReview({p,busy,save}:{p:WorkPreference;busy:boolean;save:(b:object)=>unknown}){const [note,setNote]=useState(p.reviewNote);return <form className="hr-form" onSubmit={e=>{e.preventDefault();save({action:'reviewPreference',id:p.id,version:p.version,reviewNote:note})}}><Field label="희망 근무량 검토 메모"><textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></Field><button disabled={busy}>검토 기록 남기기</button></form>}
