import {useState} from 'react';
import {SKILL_LEVELS,type HrPanelProps,type TrainingView,type BuddyAssignment,type SkillRecord} from '../../lib/hr/types';
import {Field,Empty,useHrAction,useHrData} from './components';
const stepLabels={todo:'교육 전',doing:'함께 연습 중',awaiting_ack:'직원 확인 기다림',done:'확인 완료'};
export function TrainingPanel({client,branchId,selfId,demo}:HrPanelProps){
 const {data,error,reload}=useHrData<TrainingView>(client,'/api/hr/training?branch='+encodeURIComponent(branchId));const action=useHrAction(client,branchId,reload);
 const [employeeId,setEmployee]=useState(''),[buddyId,setBuddy]=useState(''),[from,setFrom]=useState(''),[until,setUntil]=useState(''),[steps,setSteps]=useState([{title:'',manualId:''}]);
 const [skillName,setSkillName]=useState(''),[manualId,setManual]=useState(''),[skillId,setSkill]=useState(''),[target,setTarget]=useState(''),[level,setLevel]=useState<SkillRecord['level']>('교육 전'),[note,setNote]=useState('');
 if(!data)return <section className="hr-panel"><h2>신입 교육·숙련도</h2><p role={error?'alert':'status'}>{error||'교육 기록을 확인하고 있어요.'}</p><button onClick={reload}>다시 연결</button></section>;
 const people=data.people,personName=(id:string)=>people.find(e=>e.id===id)?.name||'이전 소속 직원',manualOptions=<><option value="">연결하지 않음</option>{data.manuals.map(m=><option value={m.id} key={m.id}>{m.title}</option>)}</>;
 return <><section className="hr-panel"><h2>처음 하는 일도, 같이 하면 익숙해져요.</h2><p>누가 알려 주는지, 다음에 무엇을 배우는지 분명하게. 교육 진행과 직원 확인을 따로 남겨요.</p>{action.feedback}
 {data.manage&&<details><summary>새 교육 계획 만들기</summary><form className="hr-form hr-separator" onSubmit={e=>{e.preventDefault();void action.run('/api/hr/training',{action:'assignBuddy',employeeId,buddyId,from,until,steps:steps.map(s=>({...s,manualId:s.manualId||null}))})}}><div className="hr-grid"><Field label="교육받을 직원"><select required value={employeeId} onChange={e=>setEmployee(e.target.value)}><option value="">선택해 주세요</option>{people.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="함께할 선배"><select required value={buddyId} onChange={e=>setBuddy(e.target.value)}><option value="">선택해 주세요</option>{people.filter(e=>e.id!==employeeId).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="교육 시작일"><input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="교육 종료일"><input type="date" required min={from} value={until} onChange={e=>setUntil(e.target.value)}/></Field></div>{steps.map((s,i)=><div className="hr-grid" key={i}><Field label={`${i+1}번째 배울 내용`}><input required maxLength={100} value={s.title} onChange={e=>setSteps(steps.map((s,j)=>i===j?{...s,title:e.target.value}:s))}/></Field><Field label={`${i+1}번째 연결 매뉴얼`}><select value={s.manualId} onChange={e=>setSteps(steps.map((s,j)=>i===j?{...s,manualId:e.target.value}:s))}>{manualOptions}</select></Field></div>)}<div className="hr-actions"><button type="button" disabled={steps.length>=30} onClick={()=>setSteps([...steps,{title:'',manualId:''}])}>학습 단계 추가</button><button className="hr-primary" disabled={action.busy}>교육 계획 저장</button></div></form></details>}
 {!data.buddies.length?<Empty>아직 배정된 교육이 없어요. 사장님이 선배와 학습 단계를 정하면 여기서 시작할 수 있어요.</Empty>:data.buddies.map(a=><article className="hr-separator" key={a.id}><h3>{personName(a.employeeId)}의 교육</h3><p>{a.from} ~ {a.until} · 담당 {personName(a.buddyId)}</p>{a.handover&&<p className="hr-hint">담당자의 소속이 바뀌었어요. 사장님이 새 담당자를 정해 주세요.</p>}{data.manage&&<BuddyReassign a={a} people={people} busy={action.busy} save={body=>action.run('/api/hr/training',body)}/>}<ol className="hr-learning">{a.steps.map(s=><li key={s.id}><strong>{s.title}</strong> <span className="hr-tag">{stepLabels[s.progress]}</span>{s.manualId&&<p><a href={(demo?'/demo?screen=manual&manual=':'/app?screen=manual&manual=')+encodeURIComponent(s.manualId)}>매뉴얼 열기 →</a></p>}<p>{s.note}</p>{s.staffAckAt&&<small>직원 확인 {new Date(s.staffAckAt).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})}</small>}{(data.manage||a.buddyId===selfId)&&a.employeeId!==selfId&&<StepEdit key={s.id} assignment={a} step={s} busy={action.busy} save={body=>action.run('/api/hr/training',body)}/>} {a.employeeId===selfId&&s.progress==='awaiting_ack'&&<button disabled={action.busy} onClick={()=>void action.run('/api/hr/training',{action:'ackStep',id:a.id,version:a.version,stepId:s.id})}>이 내용을 배웠어요</button>}</li>)}</ol></article>)}
 </section><section className="hr-panel"><h2>어떤 업무까지 할 수 있는지, 함께 확인해요.</h2><p>담당자가 확인한 숙련도예요. 기존 업무 태그는 확인 전 정보로 보존하고, 근무 배정이나 임금을 자동으로 바꾸지 않아요.</p>
 {data.manage&&<div className="hr-grid"><form className="hr-form" onSubmit={e=>{e.preventDefault();void action.run('/api/hr/training',{action:'saveSkill',name:skillName,manualId:manualId||null})}}><h3>확인할 업무 추가</h3><Field label="업무 이름"><input required maxLength={100} value={skillName} onChange={e=>setSkillName(e.target.value)}/></Field><Field label="업무 매뉴얼"><select value={manualId} onChange={e=>setManual(e.target.value)}>{manualOptions}</select></Field><button disabled={action.busy}>업무 추가</button></form><form className="hr-form" onSubmit={e=>{e.preventDefault();const old=data.records.find(r=>r.employeeId===target&&r.skillId===skillId);void action.run('/api/hr/training',{action:'setLevel',employeeId:target,skillId,level,note,...(old?{id:old.id,version:old.version}:{})})}}><h3>숙련도 확인</h3><Field label="확인할 직원"><select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">선택해 주세요</option>{people.filter(e=>e.id!==selfId).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="확인할 업무"><select required value={skillId} onChange={e=>setSkill(e.target.value)}><option value="">선택해 주세요</option>{data.skills.filter(s=>!s.archivedAt).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="확인한 수준"><select value={level} onChange={e=>setLevel(e.target.value as SkillRecord['level'])}>{SKILL_LEVELS.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="확인 메모"><textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></Field><button className="hr-primary" disabled={action.busy}>숙련도 확인 저장</button></form></div>}
 {!data.records.length?<Empty>아직 확인한 업무가 없어요. 연습한 뒤 담당자와 수준을 확인해 주세요.</Empty>:<ul className="hr-records">{data.records.map(r=><li key={r.id}><div><strong>{personName(r.employeeId)} · {data.skills.find(s=>s.id===r.skillId)?.name||'이전 업무'}</strong><p>{r.level} · {r.checkedAt?new Date(r.checkedAt).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'}):'확인 전'}</p><p>{r.note}</p>{r.reviewRequestedAt&&<span className="hr-tag">재확인 요청 중</span>}</div>{r.employeeId===selfId&&<button disabled={action.busy} onClick={()=>void action.run('/api/hr/training',{action:'requestReview',id:r.id,version:r.version})}>다시 확인해 주세요</button>}</li>)}</ul>}{data.legacySkills.filter(x=>x.tags.length).map(x=><p className="hr-hint" key={x.employeeId}>{personName(x.employeeId)} · 기존 업무 태그(숙련 미확인): {x.tags.join(' · ')}</p>)}</section></>;
}
function BuddyReassign({a,people,busy,save}:{a:BuddyAssignment;people:{id:string;name:string}[];busy:boolean;save:(body:object)=>unknown}){const [id,setId]=useState('');return <form className="hr-actions" onSubmit={e=>{e.preventDefault();save({action:'reassignBuddy',id:a.id,version:a.version,buddyId:id})}}><Field label="새 교육 담당자"><select required value={id} onChange={e=>setId(e.target.value)}><option value="">선택해 주세요</option>{people.filter(e=>e.id!==a.employeeId).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><button disabled={busy}>담당자 변경</button></form>}
function StepEdit({assignment:a,step:s,busy,save}:{assignment:BuddyAssignment;step:BuddyAssignment['steps'][number];busy:boolean;save:(body:object)=>unknown}){const [note,setNote]=useState(s.note);return <form className="hr-form" onSubmit={e=>{e.preventDefault();save({action:'updateStep',id:a.id,version:a.version,stepId:s.id,progress:'awaiting_ack',note})}}><Field label={s.title+' 교육 메모'}><textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></Field><div className="hr-actions"><button type="button" disabled={busy} onClick={()=>save({action:'updateStep',id:a.id,version:a.version,stepId:s.id,progress:'doing',note})}>함께 연습 중</button><button disabled={busy}>직원에게 확인 요청</button></div></form>}
